### ISSUE TITLE
VPN proposal from a third-party

### ISSUE THREAD

**Issue by chikamichi** [ruby/www.ruby-lang.org#1024]
Hi,

I've just received that email. Despite the pseudo-legal stuff at the end, I decided to share it with you, for you match the "whomever might be [the right person]".

Does it make sense to you? @hsbt @JEG2 @postmodern @stomar @makimoto @sorah @zzak @JuanitoFatas 

I guess it references https://www.privateinternetaccess.com, but the url is not even provided. Does it sound like a scam we should discard, or could it be an actual proposal, requiring at least an open discussion?

This seems to be coming from http://www.londontrustmedia.com, whose mission I couldn't really understand, but I'm dumb, so enlight me :)
```
-------- Forwarded Message --------
Subject: 	Ruby-Lang
Date: 	Thu, 12 Mar 2015 16:01:24 -0700
From: 	Joseph Craig <jcraig@londontrustmedia.com>
To: 	jd@vauguet.fr


Hello Jean-Denis, 
My name is Joseph Craig and I'm the Marketing Specialist here at Private Internet
Access. I came across the Ruby-Lang site and wanted to shoot you an e-mail as
we're interested in Private Internet Access possibly sponsoring your site or working
with on some sort of deal or partnership or some other capacity. Is there any chance
we can set up a time to go over any sort of opportunities you might have available or
if you're not the right person to speak to, can you put me in touch with whomever
might be?
Thank you!
Joseph Craig
Marketing Specialist
London Trust Media, Inc.

http://londontrustmedia.com/

Toll Free: (855) ANON-VPN 
Local: (347) LTM-WINS 
Fax: (347) 803-1582

This e-mail message is intended for the named recipient(s) above, and may contain
information that is privileged, confidential and/or exempt from disclosure under
applicable law. If you have received this message in error, or are not the named
recipient(s), please do not read the content. Instead, immediately notify the sender
and delete this e-mail message. Any unauthorized use, disclosure or distribution is
prohibited. 

London Trust Media, Inc. assumes no responsibility for any errors or omissions in
the content or transmission of this email.
```

**Comment by postmodern** [comment]
Also just got this. I have no clue what a Jekyll website for a programming language has anything to do with a Pseudo-Anonymous VPN service...

**Comment by postmodern** [comment]
I also just got recruiter spam because my email is in the [geoip](https://github.com/cjheath/geoip) gem's commit history. Recruiters are getting desperate.

**Comment by postmodern** [comment]
I forwarded the message to `accelator@londontrustmedia.com` and linked them to this issue. There are consequences to spamming.

**Comment by chikamichi** [comment]
Thank you @postmodern

**Comment by postmodern** [comment]
I received this follow up email:

<pre>
Hi postmodern,

This is far from spam.  We use ruby, so why wouldn't we want to sponsor ruby?

Let's have an open discussion, and it would be best to remove that from git due to legal issue as we move forward.

Looking forward to talking,
Andrew
</pre>

So it sounds like they want to make a donation or maybe get their logo on the site? I told them to contact RubyCentral, since they handle infrastructure costs and are a 501c3 non-profit.

**Comment by postmodern** [comment]
Maybe we should add a Donations page, so companies don't have to email contributors directly?

**Comment by chikamichi** [comment]
I bet they would still do it.

It may be no spam, but it certainly has been composed in a very spamish way, much like a generic email.

I certainly have no intention to remove "that" from GitHub (not "git"), because "that" is the "open discussion" they're asking for. That's the way we decided to do things. I would then be happy to hear from us in this very issue.

If/when the discussion needs to go private (NDA/money/legal stuff), fair enough! But we're not there yet.
