### ISSUE TITLE
Invite translators to Traditional Chinese team

### ISSUE THREAD

**Issue by JuanitoFatas** [ruby/www.ruby-lang.org#1026]
Hello!

I would like to invite @hugolu and @taylorycring to @ruby/www-ruby-lang-org-i18n-zh_tw team (need to create team?). 

Thanks, Happy Friday!!!

**Comment by hsbt** [comment]
created and invited. Have a nice weekend :octocat:

**Comment by JuanitoFatas** [comment]
Thanks @hsbt :heart:!!!!

And @hugolu, @taylorycring welcome!!!!

**Comment by hugolu** [comment]
my pleasure to join you all :)

2015-03-17 19:29 GMT+08:00 Juanito Fatas <notifications@github.com>:
