### ISSUE TITLE
404 page is not getting rendered

### ISSUE THREAD

**Issue by postmodern** [ruby/www.ruby-lang.org#1027]
https://www.ruby-lang.org/foo/

I think this is an issue with the web server.

**Comment by chikamichi** [comment]
Yep, noticed that as well. @hsbt what's your feeling?

**Comment by stomar** [comment]
For rack-jekyll, a custom 404.html page must/can be provided in the root dir. Currently there is no custom 404 page, so the default is used ("Not found").
