### ISSUE TITLE
Gitter chat room

### ISSUE THREAD

**Issue by chikamichi** [ruby/www.ruby-lang.org#1035]
I created a Gitter chat room for this project: https://gitter.im/ruby/www.ruby-lang.org

Obviously not mandatory or anything, but for those who like live feedback, it could provide a nice location where to ask questions and give answers.

Would you agree to advertise this in the README with a link to the room?

*Edit*: Gitter auto-created a pull request for this, see #1034.

@ruby/www-ruby-lang-org

**Comment by sorah** [comment]
Neutral for me.

Just a question, have you encountered any problem with GitHub Issues?

**Comment by Quintus** [comment]
Well, what’s wrong with good old IRC for group live chatting? Creating a channel on Freenode is a quick, easy, and standard way for project chatrooms that is widely accepted and not tied to any service. Chat clients are available for all platforms. And I don’t have to open up my browser just for that.

Vale,
Quintus

**Comment by hone** [comment]
I'm also -1 on hanging out on a web chat for me personally, but if enough
contributors are willing to hangout there then I think it's worth
supporting it. If not, I see little value in having it.

**Comment by joneslee85** [comment]
I did have the same reaction before, what's wrong with the IRC? Well, the reality is I find that more users use Gitter than IRC and it is also much easier to follow up with what's new on the project thanks to the tight GitHub integration.

However, if there aren't any users who find the value of having this room, I don't think it's worth to create it

**Comment by Quintus** [comment]
Trung Lê <notifications@github.com> writes:
> easier to follow up with what's new on the project thanks to
> the tight GitHub integration.

GitHub has quite a nice hooks API, and I have seen chatbots using that
one to post project information to IRC (the SFML chatroom in particular,
though they are not on Freenode). So all it takes is someone setting up
an IRC bot that posts the info it receives to the IRC channel; with
GitHub and IRC both being fairly popular, I don’t think you have to
write one yourself. There will be ready ones available.

I for my part will not use a web-based centralised chat service when I
can have a decentralised one that I can use from my terminal.

Greetings
Marvin

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F

**Comment by chikamichi** [comment]
#1034 merged.
