### ISSUE TITLE
Safari rendered image in black on load

### ISSUE THREAD

**Issue by JuanitoFatas** [ruby/www.ruby-lang.org#1053]
![screenshot 2015-04-18 13 51 45](https://cloud.githubusercontent.com/assets/1000669/7214190/1254f60e-e5d2-11e4-8f69-54bf5e29f366.png)

See: https://staging-ruby-lang.herokuapp.com/en/

I deployed v286 but found the background image rendered black, so rollbacked to v285. :bow: 

Probably related to http://stackoverflow.com/questions/10031311/safari-rendering-image-background-black-on-load. 

I can't reproduce on my local. Any ideas? Thanks!

**Comment by kkirsche** [comment]
@JuanitoFatas it's due to the PNG being corrupted. Loading the ruby_pattern.png into Photoshop gives a "Could not complete your request because the file-format module cannot parse the file."

**Comment by JuanitoFatas** [comment]
@kkirsche You are right. Thanks for the information! @hsbt Shibata san, do you know where the original photos come from? We should replace these broken image under `_site/images` folder. Thanks!

**Comment by kkirsche** [comment]
Happily @JuanitoFatas. Glad I could help

**Comment by hsbt** [comment]
I don't know.

@jzimdars Do you have original png file yet?

**Comment by jzimdars** [comment]
Sure thing. I'll just attach them here rather than pulling so I don't end up with the corrupted version.

![ruby_pattern](https://cloud.githubusercontent.com/assets/107673/7370364/45c17544-ed7f-11e4-9cb9-86246f37f1ed.png)

![ruby_pattern 2x](https://cloud.githubusercontent.com/assets/107673/7370365/45cfc342-ed7f-11e4-8381-1b55e79f2947.png)

**Comment by hsbt** [comment]
@jzimdars Thanks for your quick response!

**Comment by jzimdars** [comment]
Hmm... looks like the Ruby logo file is black, too. Are we sure there isn't something else going on?

![header-ruby-logo](https://cloud.githubusercontent.com/assets/107673/7370396/71fe25d0-ed7f-11e4-9d8f-468c4055b4c2.png)
![header-ruby-logo 2x](https://cloud.githubusercontent.com/assets/107673/7370397/71fef5aa-ed7f-11e4-9bf8-04e45ae6f1d5.png)

**Comment by huochunpeng** [comment]
Is there a reason for that I still see the black images in Safari 9 days after?

The images in the repo look ok though. Anything messed up the images during deployment?

**Comment by kkirsche** [comment]
That's what I was wondering @huochunpeng — it could very easily be a deployment infrastructure issue

**Comment by focused** [comment]
I have the same issue in Safari 8.0.5 (Yosemite)

**Comment by tadman** [comment]
Just noticed this today. The page renders correctly in Chrome and other browsers, but Safari refuses to deal and any images saved from this site won't open in Photoshop either.

The thing Safari and Photoshop have in common is they respect colour profile data present in images. It's possible that the colour profile on these images has been somehow minified or damaged in a way that renders it unreadable and produces a corrupted file.

**Comment by stomar** [comment]
Probably related to #1069. The delivered PNG file is truncated.

**Comment by stomar** [comment]
I opened a common issue for all truncation related problems, see #1073.

**Comment by stomar** [comment]
The problem should be fixed, for now. Please report if not.

**Comment by JuanitoFatas** [comment]
@stomar Thank you, awesome work!

**Comment by tadman** [comment]
Looks good again. Great!
