### ISSUE TITLE
RSS Feeds are being truncated

### ISSUE THREAD

**Issue by cgriego** [ruby/www.ruby-lang.org#1070]
The news RSS feeds are being truncated and are therefore invalid XML. This issue started May 2nd.

https://www.ruby-lang.org/en/feeds/news.rss
https://www.ruby-lang.org/de/feeds/news.rss

**Comment by stomar** [comment]
Related to #1069?

**Comment by stomar** [comment]
The problem should be fixed, for now. Please report if not.
