### ISSUE TITLE
Site broken: all served files get truncated

### ISSUE THREAD

**Issue by stomar** [ruby/www.ruby-lang.org#1073]
Almost all served content seems to get truncated. This affects pages (html), RSS feeds, images, ...

This doesn't seem to be caused by a size limit; even very small files like the hamburger logo (109 bytes) are affected.

Generating and serving the site locally works fine.

This should be the common reason for #1053, #1069, #1070.

cc @hsbt

**Comment by stomar** [comment]
Regarding the timeline:

* Heroku release v285 (06b30b1, deployed 2015/04/15 23:26:54) seems to have been ok, at least regarding problems with the ruby pattern image
* Heroku release v286 (65ba0b7) showed problems with above mentioned image and was rolled back to v285
* Next deploy: v290 (08e7f27, at 2015/05/03 11:16:42); this matches the statement that RSS feeds started being broken at about May 2nd; truncated pages were observed at May 5th

**Comment by stomar** [comment]
@hsbt Between these commits was the switch to Jekyll 2:

9b90c45e1 Thu Apr 16 15:48:20 2015 +0900

:cry:

**Comment by stomar** [comment]
Serving locally with `jekyll serve` does work, but actually that's not what the server does.
So I tried with `rackup config.ru` and got internal server errors, e.g.

    ERROR Rack::Lint::LintError: Content-Length header was 107, but should be 109

This was for images/hamburger.png; note that for this file the deployed site serves only 107 from the total 109 bytes.

_Note: I needed to (locally) remove SSL in `config.ru`, since I didn't know how to get it running with SSL._

**Comment by stomar** [comment]
I tried to fix this with 06d990e0b76b003839516c264bffaf641a04eb94, but this caused an application error, and I needed to reverted :cry:

With a local dummy application it worked...

**Comment by stomar** [comment]
To sum up: **rack-jekyll** is the problem.

* < 0.4.0 calculates wrong Content-Length headers
* 0.4.0 and 0.4.1 should work fine, but require Jekyll <2.0 (IMO for no particular reason)
* master works with Jekyll 2, but introduces automatic (re)generation of the site, which crashes on Heroku

**Comment by stomar** [comment]
Fixed(?) with c01e59d0174f35aff4ab23524624f638788ca74d: uses rack-jekyll 0.4.1, but a patched version that allows Jekyll 2.

**Comment by stomar** [comment]
@hsbt Please review.

**Comment by hsbt** [comment]
@stomar Thanks for your investigation! I confirmed you only changes jekyll version from v0.4.1. It's ok to our website.

**Comment by JuanitoFatas** [comment]
This issue can be closed right? Seems all good now! :clap:

**Comment by stomar** [comment]
Fixed for the time being.

But we need to observe the future development of rack-jekyll, I would prefer switching back to the 'official' releases.
