### ISSUE TITLE
link to shut down website in success stories

### ISSUE THREAD

**Issue by jannisch** [ruby/www.ruby-lang.org#1104]
There is a link on the success stories page (https://www.ruby-lang.org/de/documentation/success-stories) to www.43things.com which now refers to a domain parking page. According to Wikipedia, "43things.com became read-only on August 15, 2014, and shut down permanently January 1, 2015".

**Comment by JuanitoFatas** [comment]
Could you open a Pull Request to remove it? Thank you.

**Comment by jannisch** [comment]
Yes, I hope it's like you expected!

**Comment by zzak** [comment]
Thanks for your report!
