### ISSUE TITLE
Update TryRuby link

### ISSUE THREAD

**Issue by easydatawarehousing** [ruby/www.ruby-lang.org#1182]
On ruby-lang.org's sidebar there is a link 'Try Ruby! (in your browser)'. This leads to a website (TryRuby.org) that was originally created by _why and which is now hosted by CodeSchool.

This means that TryRuby.org is embedded in a commercial website. This doesn’t seem in line with the free spirit in which TryRuby was created. Also the lesson content is a bit dated and misses some important information, like if statements. It isn't very user friendly either.

That is why I created a modern, easy to use version of Tryruby earlier this year. With fully updated lesson content which is thanks to the community available in English, Spanish, Dutch and soon Brazilian-Portuguese.

Older versions of Tryruby used an irb interpreter with a web front-end. Not very secure. The new version uses Opal and runs in the webbrowser. From a hosting point of view it is only html, js, css and json. For now I am hosting it on http://tryruby.nl

I think it would be _great idea if Tryruby would be embedded within ruby-lang.org_. If you agree, please let me know and I'll be happy to create a pull request. Any suggestions are of course welcome.

**Comment by naltun** [comment]
I love this idea. Good luck. :+1:

**Comment by hsbt** [comment]
I vote up this idea. but I couldn't find tryruby's source code. Does anyone know original code of tryruby?

**Comment by easydatawarehousing** [comment]
https://github.com/easydatawarehousing/TryRuby

Ivo

**Comment by hsbt** [comment]
@easydatawarehousing Sorry, my late response. 

> I think it would be great idea if Tryruby would be embedded within ruby-lang.org.

I agreed your suggestion. I'm trying it.

**Comment by hsbt** [comment]
@easydatawarehousing Sorry, too late response. I confirmed to build and serve tryruby with your version. I hope to migrate your version into ruby-lang.org.

But We use jekyll to build to website. but tryruby use middleman. So it migration seems difficult. 

I can prepare to `tryruby.ruby-lang.org` and deploy your version to it site. How do you think about it?

**Comment by easydatawarehousing** [comment]
That's ok. One quick solution could be to do a 'middleman build'. This generates some html, css, js and json files. these could be used to create new page(s) in jekyll. Disadvantage is you will lose a lot of flexibilty for future updates.

A better solution would be to port all content to jekyll, including all translation-data and scripts for generating the json files. Do you want to port all articles as well ? or just the ruby lessons?

Preparing a branch for _tryruby.ruby-lang.org_ could be a good start. Maybe create some empty pages to show where you want to place the new content. I am certainly willing to help (starting august due to vacation).

**Comment by olivierlacan** [comment]
@hsbt If you settle for a subdomain I would suggest http://try.ruby-lang.org/, `tryruby` would be redundant since the domain is `ruby-lang.org` already. @easydatawarehousing you could simply migrate your repository to the `ruby` organization under the name `try.ruby-lang.org` and I believe the site could be hosted on GitHub pages for free.

That would certainly be a simpler solution.

**Comment by easydatawarehousing** [comment]
Sorry for the long delay. I have changed hosting of TryRuby to [Github pages](https://easydatawarehousing.github.io/TryRuby/). The old site redirects to the new location (for now, but I will cancel the hosting and tryruby.nl domain name soon).

Simplest solution would perhaps be to just change the tryruby link on ruby-lang.org to this new location?

**Comment by olivierlacan** [comment]
@easydatawarehousing Could you submit a PR with this link? 
@hsbt Does that work for you?

**Comment by olivierlacan** [comment]
@hsbt Any update on the idea of hosting this at https://try.ruby-lang.org? I'm not sure who to talk to about ruby-lang.org DNS issues, and whether we'd need approval from more Ruby core team folks?

While I deeply appreciate @easydatawarehousing's job, the url `https://easydatawarehousing.github.io/TryRuby/` feels like an ad to me. And that's coming from the guy who's maintained the Code School sponsored version of tryruby.org for years. 😄 

Since HTTPS won't work with GitHub Pages (for now) on a custom domain, I really think we could easily secure help from @hone to get this project hosted for free on Heroku forever since it should really be that resource intensive to begin with.

**Comment by hone** [comment]
@olivierlacan ruby-lang already has a sponsorship from Heroku for hosting things (ruby-lang.org is hosted on heroku afaik). We can just roll that in with that.

**Comment by hsbt** [comment]
I have a plan about `try.ruby-lang.org`:

```
The internet -> fastly(try.ruby-lang.org) -> gh-pages(https://ruby.github.io/tryruby)
```

**Comment by olivierlacan** [comment]
@hsbt I like it. Except make it `https://ruby.github.io/try)`. No need to repeat Ruby. 😸

**Comment by hsbt** [comment]
Just published https://ruby.github.io/try/

**Comment by JuanitoFatas** [comment]
Links on navbar need to be updated, now 404:

- https://ruby.github.io/TryRuby
- https://ruby.github.io/TryRuby/articles
- https://ruby.github.io/TryRuby/playground
- https://ruby.github.io/TryRuby/about

**Comment by hsbt** [comment]
@JuanitoFatas Thanks. It's too hard to rename repository name. I gave up it. I rename try to TryRuby now.

https://ruby.github.io/TryRuby/

**Comment by easydatawarehousing** [comment]
PR is updated to the new links.

**Comment by hsbt** [comment]
@easydatawarehousing Thanks. I will merge this.

**Comment by hsbt** [comment]
Deployed www.ruby-lang.org now. Huge thanks @easydatawarehousing .

**Comment by olivierlacan** [comment]
@hsbt Might be nice to redirect https://www.ruby-lang.org/try/ to it.
