### ISSUE TITLE
Translate Fukuoka Ruby Award 2016 (zh_cn)

### ISSUE THREAD

**Issue by JuanitoFatas** [ruby/www.ruby-lang.org#1193]
@ruby/www-ruby-lang-org-i18n-zh_cn Please translate [this article](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2015-10-13-fukuoka-ruby-award-2016.md) into `zh_cn` and open a Pull Request, review then merge into master branch. Thanks!

**Comment by hlcfan** [comment]
@JuanitoFatas Do you think it's OK if I add this article to https://github.com/ruby/www.ruby-lang.org/issues/1194 ?

**Comment by JuanitoFatas** [comment]
> @JuanitoFatas Do you think it's OK if I add this article to #1194 ?

ok! Translate static pages first to remove unmaintain notice. Then focus on latest news. Thanks!

**Comment by stomar** [comment]
We usually do not have issues for individual translations (would be much too many). So please add this to #1194 and close.

@hlcfan Welcome around; nice that zh_cn is going to be updated!
Please start with submitting pull requests and having them reviewed before merging them. And note that merges affecting `en` (like daa8dfd10135e215deccd0d7e46674e6ed8e2f50) should be done by the editorial team, not by i18n maintainers.

**Comment by hlcfan** [comment]
Closing.
