### ISSUE TITLE
Maintainers wanted

### ISSUE THREAD

**Issue by postmodern** [ruby/www.ruby-lang.org#120]
Many of the translations are lacking active maintainers:
- bg
  - @mytrile (current maintainer)
- es
  - @dabit (new maintainer)
  - @vic (new maintainer)
  - @hagarelvikingo (new maintainer)
- fr
  - @chatgris (volunteered)
- id
  - @gozali (new maintainer)
- it
  - @hagarelvikingo (new maintainer)
  - @gcapizzi (volunteered)
- ja (without news release, update old contents)
  - @tkhr (new maintainer)
  - @tak0303 (volunteered)
  - @trmmy (volunteered)
- ko
- pl
  - @crabonature (new maintainer)
  - @mlen (volunteered)
- pt
  - @badosu (volunteered)
- pt_br
  - @fuadsaud (new maintainer)
- ru
  - @gazay (new maintainer)
- tr
- zh_cn
  - @AndorChen (new maintainer)
  - @songjiayang (new maintainer)
  - @chenyukang (new maintainer)
- zh_tw

**Update** Please read [our maintenance policy](https://github.com/ruby/www.ruby-lang.org/wiki/Team#i18n-maintainers)

**Comment by gfvcastro** [comment]
@postmodern @dabit @hsbt: I would like to become a spanish maintainer.
