### ISSUE TITLE
Rubygarden link target with different content

### ISSUE THREAD

**Issue by victorjtfranco** [ruby/www.ruby-lang.org#1202]
The Rubygarden link (http://faq.rubygarden.org/entry/show/57?controller_prefix=faq%2F) on the page "Ruby from other languages" (https://www.ruby-lang.org/en/documentation/ruby-from-other-languages/) leads to a page with advertising and a message which says "The domain rubygarden.org may be for sale."

**Comment by stomar** [comment]
Thanks for pointing this out!

We'll update or remove that link.

**Comment by Quintus** [comment]
rubygarden.org was a site from around the time of Ruby 1.6. While it was a useful site, it has been superseded first by the Ruby Application Archive (RAA), which then has been superseded by RubyGems. Removing it is probably appropriate.

**Comment by stomar** [comment]
- "The Ruby Language FAQ", on which the RubyGarden FAQ was based, is still available, under http://ruby-doc.org/docs/ruby-doc-bundle/FAQ/FAQ.html or http://docs.ruby-doc.com/docs/TheRubyLanguageFAQ/
- "The Ruby FAQ" from RubyGarden in the Internet Archive: https://web.archive.org/web/20080603033227/http://faq.rubygarden.org/
