### ISSUE TITLE
Configure Protected Branch for master branch

### ISSUE THREAD

**Issue by JuanitoFatas** [ruby/www.ruby-lang.org#1241]
Hello @ruby/www.ruby-lang.org, GitHub has this [protected branch](https://help.github.com/articles/about-protected-branches/) new feature, let's [configure this setting](https://help.github.com/articles/configuring-protected-branches/) to protect master branch?

**Comment by hsbt** [comment]
done

**Comment by JuanitoFatas** [comment]
:+1:
