### ISSUE TITLE
mirror site (ftp.iij.ad.jp) cannot access master server

### ISSUE THREAD

**Issue by mirror-contact-iij** [ruby/www.ruby-lang.org#1291]
I'm administrator of **ftp.iij.ad.jp**.

We have new ftp server. this server was changed IP address.

I found that this server can not access to **rsync://ftp.ruby-lang.org** .

I want you to modify ACL so that it can access from the following IP address.

IP: **202.232.140.64/27**

**Comment by hsbt** [comment]
I stopped to distribute via rsync. It's hard to maintain for us.

**Comment by mirror-contact-iij** [comment]
I changed the settings to sync from **ftp://ftp.ruby-lang.org**.
It seems to work well.

Thank you.
