### ISSUE TITLE
Invite translator to Spanish team

### ISSUE THREAD

**Issue by dabit** [ruby/www.ruby-lang.org#1292]
Hi, I would love to invite @gfvcastro to become a part of the es (Spanish) translation team. He has been writing the latest contributions and his help would be a great addition to the team.

Thanks! and have a nice weekend!

**Comment by gfvcastro** [comment]
@dabit: Thanks for invite me to be a maintainer, it is a pleasure to contribute here. :smile:

**Comment by vic** [comment]
+1 for @gfvcastro joining the team :)

**Comment by hsbt** [comment]
@dabit @vic I created [www-ruby-lang-org-i18n-es](https://github.com/orgs/ruby/teams/www-ruby-lang-org-i18n-es) team. and promote dabit to team maintainer.

**Comment by hsbt** [comment]
@gfvcastro I invite you to www-ruby-lang-org-i18n-es team. Please confirm it.

**Comment by dabit** [comment]
@hsbt thanks for the help! I will close the issue now.

**Comment by gfvcastro** [comment]
@dabit @hsbt @vic: Thanks. It is a pleasure to be here. :heart:
