### ISSUE TITLE
Add CoC

### ISSUE THREAD

**Issue by matz** [ruby/www.ruby-lang.org#1297]
I decided to pick PostgreSQL CoC, so please add the following article to declare.

---
We have picked the following code of conduct based on PostgreSQL CoC, for Ruby developer's community for safe, productive collaboration. Each Ruby related community (conference etc.) may pick their own CoC.

The Ruby Community CoC

This document provides community guidelines for a safe, respectful, productive, and collaborative place for any person who is willing to contribute to the Ruby community. It applies to all "collaborative space", which is defined as community communications channels (such as mailing lists, submitted patches, commit comments, etc.).

* Participants will be tolerant of opposing views.

* Participants must ensure that their language and actions are free of personal attacks and disparaging personal remarks.

* When interpreting the words and actions of others, participants should always assume good intentions.

* Behaviour which can be reasonably considered harassment will not be tolerated.

**Comment by hsbt** [comment]
@matz We will setup this text to `www.ruby-lang.org/en/conduct` and translate supported languages.

**Comment by hsbt** [comment]
@matz Can you review this? https://staging.ruby-lang.org/en/conduct/ . I used "Code of Conduct" instead of "CoC".

**Comment by matz** [comment]
Looks good to me.

**Comment by hsbt** [comment]
@matz I deployed www.r-lo. See. https://www.ruby-lang.org/en/conduct/

**Comment by stomar** [comment]
@hsbt

/en/conduct -> /en/about/conduct ?

**Comment by hsbt** [comment]
@stomar I referred golang structure like `https://golang.org/conduct` . Could you explain your suggestion is better?

**Comment by JuanitoFatas** [comment]
Since this page will have no translation, how about `https://www.ruby-lang.org/conduct`?

**Comment by hsbt** [comment]
@JuanitoFatas In my opinion, we should translate this text for non-native english speaker.

**Comment by skade** [comment]
This is a terribly weak CoC and refuse this as a "The Ruby Community CoC"

> Each Ruby related community (conference etc.) may pick their own CoC.

Please call this the "CRuby/MRI project CoC".

Many Ruby community projects already have a code of conduct. CRuby and MRI historically have a pretty weak outreach towards community projects. It feels pretentious to call this "a community CoC". The CRuby/MRI project specifically has _no_ community workers and no community outreach by themselves. Most of the work is done by foundations like RubyCentral, Ruby Berlin or the Travis Foundation. As one of the current heads of Ruby Berlin, I have to strictly reject the wording.

Please also make clear that this CoC applies to, I recommend _only_ to the CRuby mailing lists and bug tracker.

**Comment by stomar** [comment]
A similar thought occurred to me: the title claims "Ruby Community Code of Conduct", whereas the first paragraph states (more correctly) "Ruby developer’s community".

**Comment by CoralineAda** [comment]
This document is not a code of conduct and it should not be called such. 

From https://en.wikipedia.org/wiki/Code_of_conduct:

"Effective codes of conduct include details of how to report violations."

"Studies of codes of conduct in the private sector show that their effective implementation must be part of a learning process that requires training, **consistent enforcement**, and continuous measurement/improvement."

"The proof of CoC effectiveness is when employees/members feel comfortable enough to voice concerns and believe that the organization will respond with appropriate action."

**Comment by davidcelis** [comment]
> Also, a reminder that this CoC is based on the scrapped postgres CoC: http://www.postgresql.org/message-id/56A8516B.8000105@agliodbs.com

Yes, PostgreSQL has not actually adopted a Code of Conduct yet. They're still drafting theirs. Claiming this one to be a derivative of their Code of Conduct is misleading.

**Comment by sstjohn** [comment]
@coralineada, that's totally disingenuous. The article you're quoting begins:

>A code of conduct is a set of rules outlining the social norms and rules and responsibilities of, or proper practices for, an individual, party or organization.

This Ruby Community Code of Conduct obviously meets that definition.

**Comment by jaen** [comment]
I agree that the CoC title should probably be "The Ruby Core Community Code of Conduct" or "The Ruby Developers' Community Code of Conduct" or something similar, since as afar as I understand the intent is for this document to cover only behaviour related to Ruby Core contribution process, right? In that case it should be explicitly specified in the title that this is the case.

Also, while I don't really oppose the wording, I agree that there should at least be an e-mail in the vein of coc-abuse@ruby-lang.org or something, so that people can get in touch when they feel someone is not respecting those guidelines.

> PostgreSQL CoC, for Ruby developer's community
I think that should read "PostgreSQL CoC for Ruby developers' community" (note no comma and changed possesive). Not 100% sure, so any native speaker can feel free to correct me.

**Comment by richkilmer** [comment]
For those that refer to the wikipedia definition, please note that it did not include anything regarding enforcement in the text before Feb 2, 2016 (see history of page).  The page originated on Jul 29, 2013.  I understand that communities evolve how they are using a term but it seems the term Code of Conduct predated the idea of enforcement as a requirement to be properly considered as such.  

Webster's dictionary definition of Code of Conduct is here: http://www.webster-dictionary.org/definition/code%20of%20conduct

Noun    1.    code of conduct - a set of conventional principles and expectations that are considered binding on any person who is a member of a particular group

**Comment by hsbt** [comment]
This issue is NOT discussion threads. Please comment to https://bugs.ruby-lang.org/issues/12004 or create new issue on redmine tracker.

**Comment by stomar** [comment]
@hsbt Regarding location: I thought it a good idea to integrate this page into the existing site structure.
