### ISSUE TITLE
We should not call it CoC

### ISSUE THREAD

**Issue by matz** [ruby/www.ruby-lang.org#1302]
After some discussion, I realized our "CoC" may not conform to the definition of "CoC". So let us call it "guideline". Since Ruby community is so broad and vague (both in definition and membership), we cannot set up "real" CoC as a whole.

---
The Ruby Community Conduct Guideline

We have picked the following conduct guideline based on an early draft of the
PostgreSQL CoC, for Ruby developers community for safe, productive collaboration.
Each Ruby related community (conference etc.) may pick their own Code of Conduct.

**Comment by hsbt** [comment]
Deployed https://www.ruby-lang.org/en/conduct/
