### ISSUE TITLE
German community/mailing-lists page has broken links

### ISSUE THREAD

**Issue by Papierkorb** [ruby/www.ruby-lang.org#1314]
Hi,

On https://www.ruby-lang.org/de/community/mailing-lists/ there are a bunch of broken links:

* __Wöchentliche Zusammenfassung__ still exists, but the blog wants me to buy ruby-unrelated stuff (?)
* __Ruby-Forum.org__ gives a 404 error page from Google

The other links look fine.

**Comment by stomar** [comment]
Hi, thanks for reporting!
