### ISSUE TITLE
[中文]RUBY BUG??

### ISSUE THREAD

**Issue by tanksover** [ruby/www.ruby-lang.org#1387]
http://tryruby.org/levels/1/challenges/1
在內部使用15/7無法出現數值

**Comment by JuanitoFatas** [comment]
Please use English to open an issue and tryruby is not associated with www.ruby-lang.org, thank you!

**Comment by tanksover** [comment]
Hello
I'm having trouble on ruby website

**Comment by tanksover** [comment]
https://www.ruby-lang.org/zh_tw/about/website/

**Comment by tanksover** [comment]
have a "在瀏覽器中試用 Ruby!"

**Comment by tanksover** [comment]
I lay in the internal instruction can not respond after 15/7

**Comment by JuanitoFatas** [comment]
Hi,

http://tryruby.org is not associated with www.ruby-lang.org, you can try to [contact associated owner](https://www.codeschool.com/support).

Also you can try to post your question on [mailing list](https://www.ruby-lang.org/en/community/mailing-lists/) , [stackoverflow](http://stackoverflow.com/questions/tagged/ruby), or a [local user group](https://github.com/rubytaiwan/AMA).

Thank you.
