### ISSUE TITLE
Use of “we” in news posts

### ISSUE THREAD

**Issue by Quintus** [ruby/www.ruby-lang.org#1405]
Hi everyone,

while translating the [ConFoo Vancouver 2016 post](https://github.com/ruby/www.ruby-lang.org/blob/master/en/news/_posts/2016-05-16-confoo-cfp.md) I thought about these lines (emphasis by me):

> **We** will cover travel and hotel for the speakers who require it. […] Visit **our** site to learn more. […] **We** are eagerly expecting your proposals!

This post on ruby-lang.org invokes the association that this “we” refers to the Ruby core developers, or the organisation running ruby-lang.org (RubyCentral?). I think that the use of “we” and related pronouns is best reserved for referring to the Ruby core developers themselves as ruby-lang.org is the official website of the Ruby programming language, which is best represented by its core developer team (as in “we are happy to announce Ruby 2.3.0”). Any other use of “we” is misguiding and should best be avoided.

In this particular case, I would rather have suggested to use something like (differences emphasized):

> **ConFoo** will cover travel and hotel for the speakers who require it. […] Visit **their** website to learn more. […] **They** are eagerly expecting your proposals!

What do you think?

Valete,
Marvin

**Comment by hlcfan** [comment]
👍 Make sense

**Comment by stomar** [comment]
@Quintus

I completely agree, "we" should be reserved for ruby core or the ruby-lang.org team.

Unless... what about posts signed with sth like "the ConFoo team"; still too confusing (you would have to look at the very end of the post) or acceptable?

**Comment by Quintus** [comment]
Am Sun, 05 Jun 2016 13:07:33 -0700
schrieb Marcus Stollsteimer <notifications@github.com>:

> Unless... what about posts signed with sth like "the ConFoo team";
> still too confusing (you would have to look at the very end of the
> post) or acceptable?

If moved to top and written like this:

“This is a guest post by the ConFoo team.”

I would be fine with it. Simply not using “we” however seems more
reasonable to me.

Vale,
Quintus

**Comment by stomar** [comment]
Agreed, simplest version is avoiding "we" for third-party posts.

**Comment by jonjensen** [comment]
It looks like this issue was taken care of, but never closed and should be closed.

**Comment by JuanitoFatas** [comment]
Thanks @jonjensen <3
