### ISSUE TITLE
Add Translator (ko)

### ISSUE THREAD

**Issue by marocchino** [ruby/www.ruby-lang.org#1444]
I want invite @riseshia to @ruby/www-ruby-lang-org-i18n-ko team.

Recently, He translate #1443, #1414, #1262 and review some articles.

**Comment by yous** [comment]
Nice! :+1:

**Comment by hsbt** [comment]
Added riseshia to i18n-ko team. and I promtoed @marocchino to team maintainer.

Thanks always :octocat:

**Comment by marocchino** [comment]
Thank you! @hsbt

**Comment by riseshia** [comment]
Thank you! @hsbt
