### ISSUE TITLE
Supported versions of Windows listed are 10 years out of date

### ISSUE THREAD

**Issue by ashleydavies** [ruby/www.ruby-lang.org#1447]
In the index of 'about,' the listed versions of Windows go up to XP, which was now released 15 years ago.

I propose this change:

Ruby is highly portable: it is developed mostly on GNU/Linux, but works on many types of UNIX, Mac OS X, Windows 95/98/Me/NT/2000/XP, DOS, BeOS, OS/2, etc

Ruby is highly portable: it is developed mostly on GNU/Linux, but works on many types of UNIX, Mac OS X, Windows since Windows 95, DOS, BeOS, OS/2, etc

I would normally issue a pull request with this change myself however I suspect it may be preferred if multiple languages are updated at once and I don't trust myself to get the translations sounding correct.

**Comment by riseshia** [comment]
I think it's good!
how do you want to handle this?

**Comment by ashleydavies** [comment]
I'm happy to issue a pull request for English, German and Spanish. Will do those tonight. I assume it's OK to not update every language at once.

**Comment by stomar** [comment]
@ashleydavies Thanks for pointing this out. It's really not necessary to point out any specific version (it's also not done for Mac OS X).
