### ISSUE TITLE
[ANN] staging.ruby-lang.org is sunset.

### ISSUE THREAD

**Issue by hsbt** [ruby/www.ruby-lang.org#1455]
@ruby/ruby-org-admins and i18n maintainers.

Unfortunately, We discontinue to use wildcard certificates. Therefore I only put certificates of *.ruby-lang.org to production environment.

Please use staging-ruby-lang.herokuapp.com instead of staging.ruby-lang.org for preparation of releasing.

Thank you.

**Comment by znz** [comment]
I updated https://github.com/ruby/www.ruby-lang.org/wiki/Deployment
