### ISSUE TITLE
A syntax issue

### ISSUE THREAD

**Issue by masyasha** [ruby/www.ruby-lang.org#1475]
On the Russian version of the site, there is a syntax mistake here:
https://www.ruby-lang.org/ru/downloads/ --on the main headline.
The word 'please' in Russian should be accompanied by commas ;)
For any questions contact me on richello3027@gmail.com.
I'll be happy to help anytime.

**Comment by stomar** [comment]
Like this: "Пожалуйста, ознакомьтесь с лицензией Ruby." ?
(Instead of: "Пожалуйста ознакомьтесь ...")

**Comment by masyasha** [comment]
Yep, absolutely right👍🏼 In russian "пожалуйста" is always provided by
commas.

**Comment by stomar** [comment]
Thanks!

**Comment by masyasha** [comment]
You are always welcome, it's a great honor for me to help Ruby developing,
even in such small things! ;)
