### ISSUE TITLE
To Ruby From PHP: irrelevant point

### ISSUE THREAD

**Issue by sadovnik** [ruby/www.ruby-lang.org#1481]
There's a point in list:

> Instead of naming conventions, like underscores, the standard library and extensions are organized in modules and classes.

I think it's not relevant anymore. Class naming conventions as a scoping mechanism are in the past. Instead, namespaces along with [PSR-4 autoloading](http://www.php-fig.org/psr/psr-4/) are de facto standard.

Let me know what you think about this statement and if it's makes sense I'll make a PR.

**Comment by stomar** [comment]
Sorry for the late response.

I know very little PHP. Seems like namespaces were introduced with PHP 5.3: how about the general adoption? E. g. Wordpress doesn't seem to use them.

**Comment by sadovnik** [comment]
@stomar such products like Wordpress should not be considered when we discuss general adoption of some feature of PHP. Products like Wordpress are strive to make requirements as simpler as possible, so they can run on any garbage $0.5 hosting. The latest version of Wordpress still supports PHP 5.2, no surprise they still not using namespaces.

If you see the latest PHP version usage stats you will notice that 5.5, 5.6 and 7.0 versions are prevail.

**Comment by stomar** [comment]
Granted (it was the first project that came to my mind). However, usage statistics don't really give any information about adoption of namespaces, especially about how standard library and extensions are organized. See e.g. string functions (str_replace, str_shuffle, strlen, ...) etc.

**Comment by sadovnik** [comment]
> See e.g. string functions (str_replace, str_shuffle, strlen, ...) etc.

Yes, they still haven't redesigned in some appropriate form.

> How about only "The standard library and extensions are organized in modules and classes."?

This sounds ok to me. :)
