### ISSUE TITLE
Promote meisyal to be the maintainer of Bahasa Indonesia

### ISSUE THREAD

**Issue by JuanitoFatas** [ruby/www.ruby-lang.org#1510]
@meisyal [has been active](https://github.com/ruby/www.ruby-lang.org/pulls/meisyal) translating news but PRs not getting merged, I think @meisyal can be a maintainer.

@hsbt @stomar What do you think?

**Comment by stomar** [comment]
very much agree

**Comment by hsbt** [comment]
I invited @meisyal to www.ruby-lang.org-i18n team now.

**Comment by meisyal** [comment]
Thank you for invite me to be the maintainer of Bahasa Indonesia, @hsbt. It's a pleasure to contribute here.
Thanks, @JuanitoFatas and @stomar.
