### ISSUE TITLE
Can't easily find out which versions of Ruby are supported, receiving security updates only, or neither.

### ISSUE THREAD

**Issue by threedaymonk** [ruby/www.ruby-lang.org#1521]
When working on a client project that's using an old version of Ruby, I would like to be able to find out quickly and easily:

* whether this version is still supported; and
* when support will/did end.

At the moment, I can't find this information on ruby-lang.org. Some of it is available by looking through news posts, but it's not very accessible.

Wikipedia has [a useful summary table](https://en.wikipedia.org/wiki/Ruby_(programming_language)#Table_of_versions), but it would be preferable to have a primary source to refer to.

**Comment by stomar** [comment]
Actually, I already started work on a summary page for released versions and branch status information some time ago, but I didn't have the time/motivation to finish and push upstream.

I'll take your comment as a motivation for adding this soon, maybe I can manage to push a raw version even this weekend.

cc @hsbt

**Comment by threedaymonk** [comment]
@stomar Excellent, thank you!

**Comment by hsbt** [comment]
@threedaymonk I understood your concerns. I try to publish our maintenance policy and release schedule.

**Comment by jrochkind** [comment]
There is now a list of [ruby versions and status](https://www.ruby-lang.org/en/downloads/branches/), which is great! 

Is the maintenance _policy_ which leads to this list available anywhere?  It would be helpful to understand how it's decided when versions go into what maintenance status.
