### ISSUE TITLE
Domain Apex Pointed at TLS Certificate Lacking Proper SAN

### ISSUE THREAD

**Issue by SeanSith** [ruby/www.ruby-lang.org#1527]
When browsing https://ruby-lang.org, user receives an HTTPS error message notifying the user that the common name is invalid on the certificate. A review of the certificate, as issued by Let's Encrypt Authority X3 shows that the certificate is valid for 'ftp.ruby-lang.org' only. Subsequent Permanent Redirection (301) issued by Nginx hides this from users who have previously clicked to accept the certificate.

Steps To Reproduce:
1. Open browser to https://ruby-lang.org.
2. Receive 'common name invalid' response.
3. Accept insecure certificate. (Chrome -> Advanced -> "Proceed to..." or Firefox -> "Add Exception ..." -> "Confirm Security Exception")
4. Receive 301 from Nginx to send browser to https://www.ruby-lang.org, which most browsers will cache.
5. Close window or tab.
6. Open browser to https://ruby-lang.org
7. Automatically redirect to https://www.ruby-lang.org due to having previously received 301 from Nginx.

Expected result: TLS certificate issued by Let's Encrypt Authority X3 should have 'ruby-lang.org' as an acceptable Subject Alternative Name (SAN). Presumably the hostname is canonically being used primarily for FTP access, so pointing 'ruby-lang.org' at 'www.ruby-lang.org' would be inappropriate.

**Comment by nurse** [comment]
Duplicated with https://github.com/ruby/www.ruby-lang.org/issues/2657
