### ISSUE TITLE
Creating a German ruby mailinglist on ruby-lang.org?

### ISSUE THREAD

**Issue by Quintus** [ruby/www.ruby-lang.org#1551]
Hi everyone,

I have emailed webmaster@ruby-lang.org without a reply, so I'll try it here again. The main German Ruby forum [goes out of service due to lack of someone willing to do the maintenance administration](http://forum.ruby-portal.de/viewtopic.php?f=7&t=26951) and we're discussing switching to a mailinglist which causes much less maintenance effort than a phpBB forum or generally any web forum software. There are ruby-talk, ruby-list, and ruby-fr (amongst others) [hosted on ruby-lang.org already](http://lists.ruby-lang.org/cgi-bin/mailman/listinfo), so I think it is natural to ask whether it's possible to add a ruby-de list to ruby-lang.org and give the configuration privileges to the existing moderators of the German ruby forum.

Since the concern has been voiced whether it's likely to get a spam problem, I'd like to ask whether anti-spam efforts are made for the lists on ruby-lang.org. As a susbcriber of Ruby-Talk I have rarely seen spam on the list, but it is good to know anyway.

As a wild guess into the blue, I'll just /cc @hsbt who looks to me as if he is responsible for the technical infrastructure of ruby-lang.org. If that's not the case, please forgive me and direct me to the correct person to ask.

Valete,
Quintus

**Comment by stomar** [comment]
Hi Quintus,

the mailman pages of the individual lists have @shugo as list owner in the footer, so I would guess he is responsible for lists.ruby-lang.org.

BTW. I wasn't aware of ruby-fr, and the archive is empty... it might be abandoned (but of course that doesn't concern a possible ruby-de list, just a side note).

**Comment by Quintus** [comment]
On Tue, Mar 14, 2017 at 11:27:00AM -0700, Marcus Stollsteimer wrote:
> the mailman pages of the individual lists have @shugo as list owner in
> the footer, so I would guess he is responsible for
> lists.ruby-lang.org.

I didn't notice that. Thanks for the pointer; I guess just waiting for a
reply here is okay though, rather than sending yet another email.

> BTW. I wasn't aware of ruby-fr, and the archive is empty... it might
> be abandoned

You're right. I just saw the name and assumed it's okay. ruby-list does
have an archive (on blade), just like ruby-talk.

> (but of course that doesn't concern a possible ruby-de
> list, just a side note).

Yeah. I'll think we'll wait what @shugo says then. And of course, you're
invited to join the list if it comes true :-)

Quintus

-- 
Blog: https://www.guelkerdev.de
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by Quintus** [comment]
Further investigation: https://bugs.ruby-lang.org/issues/13329

**Comment by hsbt** [comment]
Hi, I relied comment on ttps://bugs.ruby-lang.org/issues/13329 .

I will close this.
