### ISSUE TITLE
Mirror Germany

### ISSUE THREAD

**Issue by herrbischoff** [ruby/www.ruby-lang.org#1566]
I just found that the download mirror in Germany is down. Since I have bandwidth to spare, I just set one up at https://mirror.herrbischoff.com/ruby, pulling via FTP from ftp.ruby-lang.org.

Please feel free to add/replace the mirror on the list.

**Comment by hsbt** [comment]
I recommend to use https://cache.ruby-lang.org . It uses global CDN sponsored by fastly.

>I just found that the download mirror in Germany is down.

Can you point it mirror? I'm going to remove it from mirror list.

**Comment by herrbischoff** [comment]
> Can you point it mirror? I'm going to remove it from mirror list.

The mirror that is down is AmbiWeb GmbH.

> It uses global CDN sponsored by fastly.

Does this mean that you have no need for another mirror? I'd be happy to provide mine which has a 200 Mbit+ connection and about 5 TB/month of bandwidth to spare. If you don't want or need it, please let me know so I can delete the mirrored files.

**Comment by herrbischoff** [comment]
@hsbt: I'm closing this issue due to lack of interest. Should you be interested non the less, let me know.

As of right now, the german mirror is still unavailable:

> dl.ambiweb.de’s server DNS address could not be found.
