### ISSUE TITLE
Direct links to ruby packages on download page

### ISSUE THREAD

**Issue by jackoote** [ruby/www.ruby-lang.org#1587]
Every time I want to download Ruby for Windows I go to the download page on the ruby-lang.org website. This is what I see:

> We have several tools on each major platform to install Ruby:
> 
> On Linux/UNIX, you can use the package management system of your distribution or third-party tools (rbenv and RVM).
> On OS X machines, you can use third-party tools (rbenv and RVM).
> On Windows machines, you can use RubyInstaller.
> See the Installation page for details on using package management systems or third-party tools.

I cannot click anything except the word _Installation_.  It's so anti-user-friendly. I think users want to see a download button, or some instructions, for all major platforms directly on the download page. Now we have bullets points listing the platforms, even if there's nowhere to click on.
Check out [Go's dl page](https://golang.org/dl/) to see what I mean.
Anyway good job for everything. Love Ruby.

**Comment by stomar** [comment]
Thank you for the hint. I'll try to come up with an improvement as soon as I find the time.

**Comment by hsbt** [comment]
I understood your inconvenient experience.

But we are NOT Windows binary provider. so We have no responsibility for Windows (and other platforms) binaries.
