### ISSUE TITLE
/en/community/mailing-lists/index.md is linking to a unmaintained site with dead links

### ISSUE THREAD

**Issue by matkoniecz** [ruby/www.ruby-lang.org#1591]
https://github.com/ruby/www.ruby-lang.org/blob/master/en/community/mailing-lists/index.md in "comp.lang.ruby FAQ" links to the http://rubyhacker.com/clrFAQ.html

http://rubyhacker.com/clrFAQ.html has set of links in section "Table of contents".

These links are not working ("1 About Ruby" links to 404 at
http://hypermetrics.com/rubyhacker/clrFAQ.html#tag1)

http://rubyhacker.com/clrFAQ.html has "This FAQ was originally produced by Conrad Schneiker. It is now maintained by Hal Fulton." but mailto:hal9000@hypermetrics.com bounces with "Delivery Status Notification (Failure) 550 No Such User Here"

**Comment by matkoniecz** [comment]
it also links to http://dev.rubycentral.com/survey.html (in "The survey is here.").

Overall, is there any value in reading this FAQ? It seems to be a trap for people that read documentation.

If that would be useful I can make PR removing this link.

**Comment by hsbt** [comment]
I'm ok to remove 404 status pages. Can you make a PR about this issue?

**Comment by stomar** [comment]
The linked page itself is not 404. The TOC links on that page are not working (they seem to have not been updated to the current URL of the page), but the content they should link to is on the very same page.

I know that Hal Fulton still posts on ruby-talk. Did you try the contact information on http://rubyhacker.com/?

**Comment by matkoniecz** [comment]
good idea, I send a mail

**Comment by stomar** [comment]
Fixed by removing the link (and with #1592 that provides posting guidelines).
