### ISSUE TITLE
Spanish translations

### ISSUE THREAD

**Issue by gargola** [ruby/www.ruby-lang.org#1606]
Hello @stomar ,

I've noticed that the spanish translations are very out-dated and would like to collaborate with the project by fixing that. I can start right away so, please let me know what the best approach for this would be.

-gargola

**Comment by dabit** [comment]
Hi @gargola, I personally apologize for this since I've been up to my neck in work to actually make them. I'm in charge of the spanish translations.

If you send the PR, I'll review and merge it.

Thanks in advance!

**Comment by gargola** [comment]
No worries @dabit, through collaboration we can make it happen. That's the beauty of Open Source 😄  I'll start working on this right away so expect a PR pretty soon.

Thanks a lot for the prompt reply!

Regards.

**Comment by Quintus** [comment]
Now that I look into it. Cf. #1893. Looks as if there's hope for the `es` team. /cc @hsbt again
