### ISSUE TITLE
Stable Snapshot is Missing

### ISSUE THREAD

**Issue by EmpireWorld** [ruby/www.ruby-lang.org#1607]
I have tried to download latest stable snapshot but web server says not found:

https://cache.ruby-lang.org/pub/ruby/stable-snapshot.tar.gz

Also checkout the index:

https://cache.ruby-lang.org/pub/ruby/

Thanks.

**Comment by hsbt** [comment]
It's a known issue. I filed to ruby core tracker.

https://bugs.ruby-lang.org/issues/13734

It requires fixing an upstream script.

**Comment by hsbt** [comment]
this is fixed at https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/59289

**Comment by EmpireWorld** [comment]
Nice. thanks.
