### ISSUE TITLE
Remove the link to RubyForge.org on 'Libraries' page

### ISSUE THREAD

**Issue by MischaTheEvil** [ruby/www.ruby-lang.org#1668]
https://www.ruby-lang.org/en/libraries/ still contains a link to RubyForge. The platform has been shutdown by Evan in 2014(1).
Please remove the link and any other references.

(1): Source:
- https://twitter.com/evanphx/status/399552820380053505 and https://en.wikipedia.org/wiki/RubyForge

**Comment by meisyal** [comment]
Should other languages do the same?

**Comment by MischaTheEvil** [comment]
@meisyal: If you'd ask me, I'd suggest yes.

**Comment by stomar** [comment]
Sure.

**Comment by meisyal** [comment]
OK. I will do it.
