### ISSUE TITLE
"First preview release" in 2.5.0-RC1 post

### ISSUE THREAD

**Issue by Quintus** [ruby/www.ruby-lang.org#1696]
The [post on Ruby 2.5.0-rc1](https://github.com/ruby/www.ruby-lang.org/blob/6963f4242063586a70fb4d4fe4926880c1ed85f7/en/news/_posts/2017-12-14-ruby-2-5-0-rc1-released.md) says:

> Ruby 2.5.0-rc1 is the first preview release toward Ruby 2.5.0

This statement is completely identical to the wording in the [2.5.0-preview1 post](https://github.com/ruby/www.ruby-lang.org/blob/6963f4242063586a70fb4d4fe4926880c1ed85f7/en/news/_posts/2017-10-10-ruby-2-5-0-preview1-released.md). This is irritating, because only one of those two can be the "first" preview release (the 2.5.0-preview1 one, logically). The wording should be changed to say "first release candidate" or so.

Vale
Quintus

**Comment by stomar** [comment]
cc @unak, @naruse

**Comment by unak** [comment]
I think that @Quintus is right.
We should change it.
@nurse, ok?

**Comment by nurse** [comment]
yeah, correct. thanks!

**Comment by naruse** [comment]
Hey guys,

For some reason I'm getting these emails regarding rubylang but I don't work with ruby at all (I work purely with comp graphics). Maybe there is a mistake? 

Cheers ;)
Juan

**Comment by stomar** [comment]
@naruse Sorry, my mistake (this time); „nurse“ has the handle „naruse“ in the Ruby source repository, so I can imagine this mix-up happens regularly.
