### ISSUE TITLE
"To Ruby From C and C++" (it) typo

### ISSUE THREAD

**Issue by blazgrom** [ruby/www.ruby-lang.org#1704]
When describing the similarities between C++ and Ruby there is a typo when explaining that Ruby doesn't uses operator->.
The current text is 

> Rubi tuttavia non usa mai l’operatore `->`, è sempre solo `.`.  

Instead it should be 
> Ruby tuttavia non usa mai l’operatore `->`, è sempre solo `.`.

**Comment by stomar** [comment]
Thanks!
