### ISSUE TITLE
404 error when trying to access old ruby version

### ISSUE THREAD

**Issue by budmc29** [ruby/www.ruby-lang.org#1771]
Sorry if this is known, but could not find any opened or closed issues related.

Currently if you visit this page: https://www.ruby-lang.org/en/news/2004/07/21/ruby-182-preview1-released/

And then try to access that version of Ruby by going here: https://cache.ruby-lang.org/pub/ruby/1.8/ruby-1.8.2-preview1.tar.gz

You will get a Nginx 404 page.
This applies to some other versions as well.

**Comment by hsbt** [comment]
We lost old packages.

**Comment by hsbt** [comment]
@budmc29 I restored some lost packages for 1.8 preview releases. You can download them now.

Thank you for notify me.
