### ISSUE TITLE
Dates are incorrect on English main page

### ISSUE THREAD

**Issue by PierreMesure** [ruby/www.ruby-lang.org#1795]
Hey,

On the English [main page](https://www.ruby-lang.org/en/), the dates for all the articles are 28 mar 2018. This is not the case on the pages of other languages.

![capture d ecran 2018-05-14 a 12 45 49](https://user-images.githubusercontent.com/7223028/39993024-c9fc612c-5774-11e8-8c94-37a66465ae86.png)

**Comment by hsbt** [comment]
It's intentional articles. All articles were published same day.

**Comment by PierreMesure** [comment]
Really? Sorry, then.
