### ISSUE TITLE
Two-factor auth removal / re-adding

### ISSUE THREAD

**Issue by Quintus** [ruby/www.ruby-lang.org#1822]
Hi everyone,

on 2018-08-08 I was forcibly removed from the "ruby" organisation without prior annoncement because I didn't have two-factor auth enabled on GitHub. I have to say that at least some kind of announcement in advance would have been nice.

Anyway, I have enabled two-factor auth now. @hsbt, @bovi, @stomar or whoever is in charge of the "Ruby" organisation with regard to the German translation team, please re-add me to "Ruby" and assign me to the German translation team again.

Quintus

**Comment by meisyal** [comment]
Hi @Quintus,

The same thing happened to me. I have contacted @hsbt via e-mail. He said that for those who removed from Ruby Programming Language organization, will be added to the organization again after 2FA enabled on GitHub account.

Yeah, I agree with you. At least, there is prior announcement.

**Comment by meisyal** [comment]
Hi @Quintus,

The same thing happened to me. I have contacted @hsbt via e-mail. He said that for those who removed from Ruby Programming Language organization, will be added to the organization again after 2FA enabled on GitHub account. Well, actually, there is announcement. You can find it [here](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/88332).

**Comment by Quintus** [comment]
Am 11. August 2018 um 08:14 Uhr -0700 schrieb Andrias Meisyal:
> Well, actually, there is announcement. You
> can find it [here](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/88332).

I see. Are all members of the ruby-lang.org translation teams expected to
subscribe to ruby-core? I thought that mailinglist was for discussing
the development of Ruby itself.

@hsbt please re-add me then.

Quintus

-- 
Blog: https://mg.guelker.eu
PGP/GPG ID: F1D8799FBCC8BC4F

**Comment by hsbt** [comment]
@Quintus I did invite you again.

I'm sorry my unfamiliar experience for you. But I need to make decisions without a discussion about the security issue. I have a responsibility to keep this organization.

**Comment by Quintus** [comment]
Thanks! I understand your reasons.

I've accepted the invitation.
