### ISSUE TITLE
Previewing the website instructions

### ISSUE THREAD

**Issue by VagishVela** [ruby/www.ruby-lang.org#1848]
Looking at the current instructions: [README.md#preview-locally](https://github.com/ruby/www.ruby-lang.org/blob/master/README.md#preview-locally)

I think we could make it easier and use ```jekyll serve``` which will bring it up on ```localhost:4000```.

I was wondering why we had different instructions, and whether this was for backward compatibility for older versions of ruby and/or jekyll?

EDIT: I also created a PR to update the text (#1849)

**Comment by stomar** [comment]
See explanation in #1849.
