### ISSUE TITLE
I would like to become editor for Spanish team

### ISSUE THREAD

**Issue by vtamara** [ruby/www.ruby-lang.org#1893]
I'm following the procedure I see at: https://github.com/ruby/www.ruby-lang.org/wiki/Become-a-maintainer

Although the spanish editorial team already has 4 members:

1. The news in spanish are extremely delayed
2. This year I didn't see any translation to spanish from a member of the editorial team
3. To help in the translation process to spanish,  I have sent some pull requests, but the reviewing and/or merging has taken too long .   For example: (a) #1705 was sent 23.Dec.2017, reviewed 26.Dec.2017, improved 3.Jan.2018 but merged only 25.Apr.2018 (and not even by an editor).   (b) 15 days ago I sent one pull request (#1876), but it has not been reviewed, (c) 8 days ago I sent 2 pull requests (#1882 and #1884) that have not been reviewed; (d) 7 days ago I sent other 3 pull requests (#1885, #1886, #1887) that have not been reviewed.  
4. I see another translation to spanish that has not been handled for almost one and half year (#1605 ).   Since the submitter is not applying the changes I proposed in the review of July.2017, IMHO it should be merged and after corrected.

**Comment by Quintus** [comment]
cc @hsbt (who AFAIK is in charge of adding team members, but he's always very busy, so expect some delay)

**Comment by dabit** [comment]
Hi @vtamara 

First of all: thank you for your contributions.

Second of all: I apologize for dropping the ball this year on the (es) part of the site, promise to become more active soon.

I used to be able to edit Teams but it looks like I lost the privilege. 

I will start reviewing all your request ASAP and merging them.

I hope someone else can add you to the team soon.

**Comment by dabit** [comment]
Everything new reviewed and merged. Thanks again @vtamara. I will be ready for your future PRs.

**Comment by vtamara** [comment]
Thank you @dabit . IMHO #1605  can be merged and after some corrections can be applied.

In other hand regarding translation of older news I see that there were some news of this year and previos years that were not translated.   Don't you think it would be a good goal to translate all the news of 2018 ?

**Comment by vtamara** [comment]
https://github.com/ruby/www.ruby-lang.org/pull/2067 has not been reviewed in 13 days.

**Comment by JuanitoFatas** [comment]
Ping @hsbt  🏓

**Comment by hsbt** [comment]
I send the invitation to @vtamara

**Comment by vtamara** [comment]
Accepted, thank you.
