### ISSUE TITLE
Ruby 2.6.0-rc1 news contains only 

### ISSUE THREAD

**Issue by PikachuEXE** [ruby/www.ruby-lang.org#1915]
https://www.ruby-lang.org/en/news/2018/12/06/ruby-2-6-0-rc1-released/
![screen shot 2018-12-07 at 4 25 10 pm](https://user-images.githubusercontent.com/1018543/49636154-b830fc80-fa3c-11e8-98cc-4da5d8f7ffbb.jpg)

**Comment by yous** [comment]
#1911 is not deployed yet.
