### ISSUE TITLE
I'd like to be part of the Portuguese i18n team

### ISSUE THREAD

**Issue by vnbrs** [ruby/www.ruby-lang.org#1931]
Hi! I'm Vinicius, and I'd like to be a maintainer to help the team with the Portuguese translations. I'm Brazilian and I love Ruby ❤️ 

The news in Portuguese are quite delayed, and I think I can be a great help to the team in order to accelerate these translations 🇧🇷 🇵🇹

**Comment by stomar** [comment]
Welcome and already thanks for your commitment.

I‘d suggest you start with a couple of PRs, to get some feedback from other maintainers. And make sure to also have a brief look at the [wiki](https://github.com/ruby/www.ruby-lang.org/wiki).
