### ISSUE TITLE
Translation to spanish not updated in https://www.ruby-lang.org/es/

### ISSUE THREAD

**Issue by vtamara** [ruby/www.ruby-lang.org#1948]
I wonder why the page in spanish is still not upated with the last merge (of the last year):

https://github.com/ruby/www.ruby-lang.org/commit/fd1ae53d21941dae7423a02bfe49a30b4816b7d6

![screencapture-ruby-lang-org-es-2019-01-18-06_05_45](https://user-images.githubusercontent.com/701221/51383358-3aeeb200-1ae7-11e9-9b9c-0b98159d5781.png)

**Comment by vtamara** [comment]
In my humble opinion it is important to keep current information for spanish speakers to gain spanish audience and programmers

**Comment by yous** [comment]
The site is not deployed at least from 26e3629b8b3b855966120960010ec7e491a9a606.

**Comment by JuanitoFatas** [comment]
Deployed c3e2ff68 to production.

**Comment by vtamara** [comment]
Thanks
