### ISSUE TITLE
HOST in Rakefile should be a localhost

### ISSUE THREAD

**Issue by ismailarilik** [ruby/www.ruby-lang.org#1977]
Hi.

I think HOST variable in Rakefile should be a localhost such as 'localhost:9292'. In development environment we are testing the changes for this environment. Now `check:markup` task uses 'www.ruby-lang.org' as its host but it is not useful for a local environment. So it should be changed. Checking main site may be done in another environment such as a CI environment.

I don't want to open a PR because I didn't know what is the reason behind this setting. Also I couldn't find any reasonable reason for it in history.

What is your thought about it? Am I wrong about anything?

**Comment by spk** [comment]
Hi,

Thanks for the feedback @ismailarilik ; if you are talking about https://github.com/ruby/www.ruby-lang.org/blob/master/Rakefile#L11 you are right its for the `check:markup` that use [validate-website](https://github.com/ruby/www.ruby-lang.org/blob/master/lib/markup_checker.rb#L8) and require a website as argument but in fact the check is done with files locally build-ed.

If its not clear maybe we should print instead the path checked ? and bug could be reported to https://github.com/spk/validate-website

**Comment by stomar** [comment]
I removed HOST in 2bcc020a21c6603ba5b717991e51a23ade9eda05, since displaying the URL while not checking it but the local files is confusing, see #1420.
