### ISSUE TITLE
Forbidden code point errors in several news (zh_cn)

### ISSUE THREAD

**Issue by ismailarilik** [ruby/www.ruby-lang.org#1982]
When I ran bundle exec rake check:markup for localhost, I got these errors:

```sh
* zh_cn/news/2018/11/06/ruby-2-6-0-preview3-released/index.html
ERROR; line 159: Forbidden code point U+0008.

* zh_cn/news/2018/12/06/ruby-2-6-0-rc1-released/index.html
ERROR; line 160: Forbidden code point U+0008.

* zh_cn/news/2018/12/15/ruby-2-6-0-rc2-released/index.html
ERROR; line 160: Forbidden code point U+0008.
```

I found related code points:

1. zh_cn\news\_posts\2018-11-06-ruby-2-6-0-preview3-released.md (Line 58)
2. zh_cn\news\_posts\2018-12-06-ruby-2-6-0-rc1-released.md (Line 59)
3. zh_cn\news\_posts\2018-12-15-ruby-2-6-0-rc2-released.md (Line 59)

But I couldn't fix since I don't know this language.

@AndorChen @hlcfan @bovi @chenyukang

**Comment by hlcfan** [comment]
This should be fixed in #1986, please try again, thanks!

**Comment by ismailarilik** [comment]
I have checked; it seems OK. I am closing the issue. Thank you!

**Comment by hlcfan** [comment]
Thanks @ismailarilik!
