### ISSUE TITLE
Forbidden code point errors in several news (zh_tw)

### ISSUE THREAD

**Issue by ismailarilik** [ruby/www.ruby-lang.org#1983]
When I ran bundle exec rake check:markup for localhost, I got these errors:

```sh
* zh_tw/news/2017/12/27/fukuoka-ruby-award-2018/index.html
ERROR; line 143: Forbidden code point U+0008.

* zh_tw/news/2018/11/29/fukuoka-ruby-award-2019/index.html
ERROR; line 143: Forbidden code point U+0008.
```

I found related code points:

1. zh_tw\news\_posts\2017-12-27-fukuoka-ruby-award-2018.md (Line 48)
2. zh_tw\news\_posts\2018-11-29-fukuoka-ruby-award-2019.md (Line 48)

But I couldn't fix since I don't know this language.

@JuanitoFatas

**Comment by bugtender** [comment]
Thanks, I'll fix it later.

**Comment by ismailarilik** [comment]
I have checked; it seems OK. I am closing the issue. Thank you!
