### ISSUE TITLE
Please remove @skade (myself) from the German translation team and the organisation

### ISSUE THREAD

**Issue by skade** [ruby/www.ruby-lang.org#2034]
Hi everyone,

It's been a lovely time! But given that I have never contributed as much to www.ruby-lang.org and am now busy with other endeavours, I would like to be removed from the teams here.

It was a great opportunity to help out ruby-lang a little and I still remain close to the community, but in the interest of safety, it would be better to remove my effectively unused access.

Best,
Florian

**Comment by skade** [comment]
Ugh, found the "leave" button myself.

**Comment by JuanitoFatas** [comment]
Thank you for all the hard work, Florian! ❤️💜💛💙💚💗💞💓💕💖💝💘

**Comment by Quintus** [comment]
> Thank you for all the hard work, Florian!

I second this.
