### ISSUE TITLE
Feature suggestion: Ruby releases and branches as structured data

### ISSUE THREAD

**Issue by eliotsykes** [ruby/www.ruby-lang.org#2066]
It'd be handy to have a structured data source that a script can consume showing the Ruby version release history, including the info that is on the [releases](https://www.ruby-lang.org/en/downloads/releases/) and [branches](https://www.ruby-lang.org/en/downloads/branches/) pages. 

This would help automating detection of when it is time to update Ruby.

**Comment by dentarg** [comment]
Maybe [`_data/releases.yml`](https://github.com/ruby/www.ruby-lang.org/blob/master/_data/releases.yml) is enough?

**Comment by eliotsykes** [comment]
Thanks @dentarg, yes, that would certainly work, using the raw response at https://raw.githubusercontent.com/ruby/www.ruby-lang.org/master/_data/releases.yml

**Comment by siaw23** [comment]
Can we close this maybe? @eliotsykes @hsbt :)
