### ISSUE TITLE
I would like to become editor for Portuguese team

### ISSUE THREAD

**Issue by jcserracampos** [ruby/www.ruby-lang.org#2112]
I'm following the procedure I see at: https://github.com/ruby/www.ruby-lang.org/wiki/Become-a-maintainer

- As you can see from my commits history, I've been contributing to this translation.

- I also have experience [translating the React documentation](https://github.com/reactjs/en.reactjs.org/commits?author=jcserracampos).

- In recent months the translation into Portuguese is practically stopped.

- I have an open PR two months ago and no one to approve #2058 .

- I personally aim to translate all publications into Portuguese for historical reasons.

**Comment by hsbt** [comment]
Hello, thanks to all your contributions.

I create `www-ruby-lang-org-i18n-pt` team and invite you.

**Comment by jcserracampos** [comment]
@hsbt Thank you.
I didn't get the team invite.

**Comment by hsbt** [comment]
Note: I promote @jcserracampos as team maintainer.
