### ISSUE TITLE
Broken links on /about/website

### ISSUE THREAD

**Issue by jonjensen** [ruby/www.ruby-lang.org#2124]
Something is wrong with the way links to this very GitHub repo are included on the page:

https://www.ruby-lang.org/en/about/website/

For example in:

> To report a problem use the issue tracker or contact our webmaster (in English).

There, "issue tracker" points to http://www.ruby-lang.org/issues but should point to https://github.com/ruby/www.ruby-lang.org/issues and indeed is set up to point there in `en/about/website/index.md`.

Something in the static site generator appears to be seeing `www.ruby-lang.org` in the URL path and mistakenly treating that and the hostname before it as the hostname instead of an absolute URL to github.com.

Same problem here:

> If you wish to contribute, read the contribution instructions and just start opening issues or pull requests!

where "contribution instructions" points to http://www.ruby-lang.org/wiki but should point to https://github.com/ruby/www.ruby-lang.org/wiki.

I looked around a bit but didn't find the culprit code.

**Comment by Stevyb0t** [comment]
All of the link you've listed are fine for me. Both of them redirect correctly to GitHub.

**Comment by jcserracampos** [comment]
It works fine for me too.

@jonjensen can you check again?

**Comment by jonjensen** [comment]
@jcserracampos @Stevyb0t Yes, someone seems to have fixed in and they work for me now. Thanks!
