### ISSUE TITLE
[ja] link 404

### ISSUE THREAD

**Issue by okuramasafumi** [ruby/www.ruby-lang.org#2151]
https://www.rubyist.net/~kazu/samidare/
The link is shown on the top page of Japanese site, but is 404 when I visit.

Should it be simply deleted? Is there any alternative?

**Comment by znz** [comment]
Old www.rubyist.net (boron.rubyist.net) stopped. ([[ruby-list:50774]](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-list/50774) is announcement before stopping.)
And I did not use it recent years, so it did not move to somewhere.
