### ISSUE TITLE
Update spanish translation of page /

### ISSUE THREAD

**Issue by vtamara** [ruby/www.ruby-lang.org#2244]
- [x] Translate completely the programming example (e.g Londres instead of London, visitadas instead of visitado)
- [x] In the programming example `Superfluo:` should be in different line and better `Son superfluos:`
- [x] Section "Explora un nuevo mundo" doesn't have translation for "Academic research"

**Comment by agarcia-caicedo** [comment]
I want to work on this issue

**Comment by aleksandrilyin** [comment]
Hello @vtamara!
On the second item may be better to leave in capital letters because upcase method?

**Comment by vtamara** [comment]
You are right @aleksandrilyin 
Thanks
