### ISSUE TITLE
Update spanish translation of /community

### ISSUE THREAD

**Issue by vtamara** [ruby/www.ruby-lang.org#2247]
- [ ] Falta traducir Podcast

**Comment by maitrella** [comment]
Me gustaría poder colaborar con el proyecto. ¿Está disponible la tarea?. 

Entiendo que habría que incluir la sección de podcast en el index.md de es\community y después replicar la esctructura del directorio podcast con su index.md correspondiente. ¿Es así?.

**Comment by vtamara** [comment]
Muchas gracias!

¡Si la tarea estaba disponible y la hizo muy bien!

Hay un par de correcciones por hacer, le hice las sugerencias como comentarios a la solicitud de cambio.
