### ISSUE TITLE
Privacy Disclosures Policy?

### ISSUE THREAD

**Issue by hanachin** [ruby/www.ruby-lang.org#2294]
https://www.ruby-lang.org/ uses Google Analytics.

https://github.com/ruby/www.ruby-lang.org/blob/e54ab05d97618d81cd6229a0d5b749e7d67fc6ff/_layouts/default.html#L78
https://github.com/ruby/www.ruby-lang.org/blob/e54ab05d97618d81cd6229a0d5b749e7d67fc6ff/_includes/analytics.html#L9

But there is no privacy policy
https://www.google.com/search?q=site%3Awww.ruby-lang.org+privacy+policy

Google Analytics Help page says:

> When you use Google Analytics on your site or application, you must disclose the use of Google Analytics and how it collects and processes data.
https://support.google.com/analytics/answer/7318509?hl=en

**Comment by VagishVela** [comment]
Also there is a GDPR concern, if you are using cookies you may need to have a cookie consent in the EU.

**Comment by stomar** [comment]
AFAIK we could get rid of Google Analytics, I'm not sure it's actually used.

**Comment by hsbt** [comment]
Fixed by https://github.com/ruby/www.ruby-lang.org/pull/2722
