### ISSUE TITLE
Update Turkish translation from welcome page burger menu "Home" button in mobile view

### ISSUE THREAD

**Issue by hasantezcan** [ruby/www.ruby-lang.org#2295]
I think that is forgotten. It has to be fix.
![](https://i.hizliresim.com/JVgAqY.jpg)

**Comment by ismailarilik** [comment]
It cannot be changed since it is in a common place for all translations: https://github.com/ruby/www.ruby-lang.org/blob/master/_layouts/default.html#L46

**Comment by ismailarilik** [comment]
But "Home" navigation link may be included in _config.yml just like any other links such as "Download" and "Documentation". @ruby/www-ruby-lang-org-editorial what are your opinions about this idea?

**Comment by hasantezcan** [comment]
Definitely. We can move the **"Home"** section to **_config.yml**. In this way we solved that hardcoded problem. By the way the other languages translations are needed it that changes too.

**Comment by stomar** [comment]
I prepared a fix in #2312.

**Comment by hasantezcan** [comment]
I added the Turkish translation. 
#2330

**Comment by stomar** [comment]
Fixed with #2312 and #2330.
