### ISSUE TITLE
https://ruby-lang.org/ cert problem...

### ISSUE THREAD

**Issue by Neustradamus** [ruby/www.ruby-lang.org#2342]
There is a cert problem for https://ruby-lang.org/.

In the same time, why it is not possible to have the main website:
- https://ruby-lang.org/

Redirection to https://ruby-lang.org/ for:
- http://ruby-lang.org/
- http://www.ruby-lang.org/
- https://www.ruby-lang.org/

**Comment by MikeRogers0** [comment]
For reference, the SSL cerificate problem for `https://ruby-lang.org/`  is that the [common name](https://www.sslshopper.com/ssl-checker.html#hostname=ruby-lang.org) is set to `lists.ruby-lang.org`.

![image](https://user-images.githubusercontent.com/325384/72521872-44bf0880-3854-11ea-9836-427df5601216.png)

![image](https://user-images.githubusercontent.com/325384/72521885-4c7ead00-3854-11ea-8b05-ccc5196e03df.png)

**Comment by znz** [comment]
I think A record of `ruby-lang.org` should be removed if it is not used.
MX record of `ruby-lang.org` exists and points to other host, so mail server is not affected.

@shugo How is it?

**Comment by shugo** [comment]
I've removed the A record.

**Comment by jack-the-coder** [comment]
Can this be configured to redirect to https://www.ruby-lang.org? Now that the Chrome omnibox no longer displays the www. subdomain, it is confusing to type ruby-lang.org and get a "server not found" error while opening the page from a search engine shows "ruby-lang.org/en/" in the address bar. 

It appears that you use Fastly (based on the issuer of your SSL certificate), so I think this would be configured from there.

**Comment by Neustradamus** [comment]
Hi all,

A website which explain:
- https://dropwww.com/why

**Comment by thiagogabriel** [comment]
In the current DNS configuration `ruby-lang.org` doesn't point anywhere.

```bash
~ % curl ruby-lang.org
curl: (6) Could not resolve host: ruby-lang.org
~ % curl https://ruby-lang.org
curl: (6) Could not resolve host: ruby-lang.org
~ % curl http://ruby-lang.org
curl: (6) Could not resolve host: ruby-lang.org
```
