### ISSUE TITLE
Add Japanese translation of /en/conduct

### ISSUE THREAD

**Issue by FumiyaShibusawa** [ruby/www.ruby-lang.org#2346]
There is no Japanese translation for /en/conduct page. Let me translate it so ruby related communities or events in Japan can easily pick up some of its contents.

**Comment by hig4dm** [comment]
I like this app

**Comment by jinroq** [comment]
Hi, @matz 

Where are you listning? Where can we be constructive?
See also [this tweet](https://twitter.com/yukihiro_matz/status/1082426622928609280).

Please tell us your consider after releasing Ruby 3.1.0.

Thanks.

**Comment by matz** [comment]
The quality of the translation has been the blocking issue. See my comment in #2347
Sorry for leaving this for a long time.
