### ISSUE TITLE
Issue in the about page

### ISSUE THREAD

**Issue by FabioCentrella94** [ruby/www.ruby-lang.org#2373]
At the bottom of the following page in the Acknowledgement section, there is a bug displaying.

[https://www.ruby-lang.org/en/about/website/](url)

![Screenshot 2020-02-19 at 18 08 16](https://user-images.githubusercontent.com/54071536/74862409-ffef2b80-5343-11ea-8da4-8275c36965e1.png)

**Comment by stomar** [comment]
Good catch, thanks for reporting!
