### ISSUE TITLE
The link to xmp is broken

### ISSUE THREAD

**Issue by ngzhio** [ruby/www.ruby-lang.org#2433]
https://github.com/ruby/www.ruby-lang.org/blob/dfa7e9d5249f065ef4cb3b1ae96772bfd54721e2/en/documentation/faq/1/index.md#L294

**Comment by hsbt** [comment]
Can you create the pull request to remove them?

**Comment by ngzhio** [comment]
> Can you create the pull request to remove them?

Remove them? Isn't there any new address of `xmp`?

**Comment by hsbt** [comment]
Feel free to choose them. I have no opinion for it.

**Comment by siaw23** [comment]
I think this should be closed as merged from https://github.com/ruby/www.ruby-lang.org/pull/2523 @hsbt @yous
