### ISSUE TITLE
Feedback to the Ruby Core team

### ISSUE THREAD

**Issue by sandstrom** [ruby/www.ruby-lang.org#2451]
*Couldn't find a feedback form, perhaps this channel works.*

I really like Ruby, but here are some thoughts on areas that could improve.

## Documentation improvements
- Documentation in ruby, especially for the standard-lib + language itself, could be improved, language wise 
- UI for docs feels dated (https://ruby-doc.org/docs/ruby-doc-bundle/UsersGuide/rg/whatisruby.html) 
- There is no warning looking at old docs, python has "This document is for an old version of Python that is no longer supported. You should upgrade, and read the Python documentation for the current stable release." 
- Make deprecated things less visible in the docs.

## Make contributions easier 
- Move Ruby development to Github, to make contributions easier? 
- Update some of the internal tooling, to make it easier to follow discussion (hidden in https://bugs.ruby-lang.org). Perhaps by using a bi-directional sync with Github issues?
- Add a feedback form to the website.

## Language deprecation & spring cleaning 
- Deprecate the special globals, replace with other things: https://ruby-doc.org/docs/ruby-doc-bundle/UsersGuide/rg/globalvars.html 
- Remove some rarely used packages from stdlib, e.g. extmk, rinda, un, win32ole https://ruby-doc.org/stdlib-2.7.1/

**Comment by hsbt** [comment]
Thanks for your idea. But this repository only handle www.ruby-lang.org. You should post them to bugs.ruby-lang.org.
