### ISSUE TITLE
Missing "Ruby C API Reference" on Documentation page

### ISSUE THREAD

**Issue by VagishVela** [ruby/www.ruby-lang.org#2516]
On [Documentation](https://www.ruby-lang.org/en/documentation/) the below link goes to a 404:
<img width="582" alt="Screen Shot 2020-10-21 at 9 33 56 AM" src="https://user-images.githubusercontent.com/7334882/96727121-b9454b80-1380-11eb-96a4-a44e918d65ec.png">
Link: https://docs.ruby-lang.org/en/master/extension_rdoc.html

I couldn't find a replacement document, also the [Wayback Machine](https://web.archive.org/web/*/https://docs.ruby-lang.org/en/master/extension_rdoc.html) yielded 0 results too.

I can create a PR to remove it, not sure if there is a reason not to.

**Comment by yous** [comment]
This seems to be the correct link: <https://docs.ruby-lang.org/en/master/doc/extension_rdoc.html>

**Comment by VagishVela** [comment]
Closing this as the PR has been merged!
