### ISSUE TITLE
Unaccessible binary distribution of 1.4.3 for the Acorn link

### ISSUE THREAD

**Issue by VagishVela** [ruby/www.ruby-lang.org#2524]
On: https://www.ruby-lang.org/en/documentation/faq/3/:

> I do provide a binary distribution of 1.4.3 for the Acorn at http://www.cl.cam.ac.uk/users/rrt1001/ruby.zip.

The link redirects you to a Google login screen. Seems like it requires authentication.

Thoughts on removing this?

**Comment by jcserracampos** [comment]
This section is outdated.
Perhaps we can remove.

**Comment by hsbt** [comment]
Fixed at https://github.com/ruby/www.ruby-lang.org/pull/2532
