### ISSUE TITLE
ruby-lang.org doesn't resolve without www

### ISSUE THREAD

**Issue by olivierlacan** [ruby/www.ruby-lang.org#2551]
There doesn't seem to be a wildcard record for ruby-lang.org: 

```
$ dig +short ruby-lang.org
$ ping ruby-lang.org
ping: cannot resolve ruby-lang.org: Unknown host
```

Meanwhile www.ruby-lang.org seems fine: 
```
$ dig +short www.ruby-lang.org
dualstack.m.shared.global.fastly.net.
151.101.1.178
151.101.65.178
151.101.129.178
151.101.193.178
$ ping www.ruby-lang.org
PING dualstack.m.shared.global.fastly.net (151.101.1.178): 56 data bytes
64 bytes from 151.101.1.178: icmp_seq=0 ttl=56 time=17.817 ms
64 bytes from 151.101.1.178: icmp_seq=1 ttl=56 time=18.123 ms
```

Any reason for not having *.ruby-lang.org at least redirect to www unless a subdomain is defined?

This was referenced in a previous issue this summer but doesn't seem to be addressed: https://github.com/ruby/www.ruby-lang.org/issues/2342#issuecomment-639474496

**Comment by hsbt** [comment]
Because we used heroku for www.ruby-lang.org. I have no idea to redirect ruby-lang.org to www.ruby-lang.org using only DNS or CDN.

I can redirect it if we use IaaS like AWS directly or prepare the simple redirector for ruby-lang.org with heroku. We have not enough human resource. I want not to setup new server or application resource.

Do you have any solution for this?

**Comment by Neustradamus** [comment]
@olivierlacan: Thanks for this new ticket.
@hsbt: If you can see about: https://dropwww.com/why, it will be nice.
I have explained in the previous ticket. Thanks in advance.

**Comment by nurse** [comment]
We say it's technically difficult in current our technology stack.

**Comment by Neustradamus** [comment]
@nurse: Do you need help, what is exactly your current infra stack?

**Comment by mame** [comment]
I'm unsure but it seems to cost money.

https://docs.fastly.com/en/guides/using-fastly-with-apex-domains
> Fastly offers the following anycast options to all paid customers.

**Comment by olivierlacan** [comment]
I'd like to reiterate that regardless of cost or complication, this should be done. @schneems is this something you could assist with given the hosting is on Heroku?

**Comment by schneems** [comment]
I can help with the heroku side but not the fastly side. Sounds like fastly is the issue? What's the heroku app name?

**Comment by JuanitoFatas** [comment]
> What's the heroku app name?

https://dashboard.heroku.com/apps/www-ruby-lang

**Comment by schneems** [comment]
You have to add it to the app via the `heroku domains` command. Once you're done you should see both the `www` and non-www domain. Here's an example with my app CodeTriage that has a Heroku app name of `issuetriage`: 

```
$ heroku domains -a issuetriage
=== issuetriage Heroku Domain
issuetriage.herokuapp.com

=== issuetriage Custom Domains
Domain Name        DNS Record Type DNS Target                       SNI Endpoint
codetriage.com     ALIAS or ANAME  codetriage.com.herokudns.com     undefined
www.codetriage.com CNAME           www.codetriage.com.herokudns.com undefined
```

Once that is set up then either you could simply serve the site from the apex domain. Or you could set up a redirect via something like rack-redirect to the `www` subdomain (I recommend a redirect if possible).

I'm not sure how fastly is setup but I'm guessing they're just caching whatever you're outputting. So maybe configuring this is good enough?

```
$ heroku domains:add ruby-lang.org -a <app-name-here>
```

You also need to set the DNS to point at the right location. These are my DNSimple DNS settings for codetriage 

![](https://www.dropbox.com/s/y5p2aire4godas8/Screen%20Shot%202021-04-05%20at%2011.33.51%20AM.png?raw=1)

> Note: The `alias` is not a standard record, but is required for SSL on the apex domain. We talk about that here https://devcenter.heroku.com/articles/custom-domains#configuring-dns-for-root-domains

**Comment by nurse** [comment]
You can use `dig` and get current configuration:
```
%  dig ruby-lang.org

; <<>> DiG 9.10.6 <<>> ruby-lang.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58738
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;ruby-lang.org.			IN	A

;; AUTHORITY SECTION:
ruby-lang.org.		900	IN	SOA	ns-1439.awsdns-51.org. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 34 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Apr 07 14:01:38 JST 2021
;; MSG SIZE  rcvd: 113

%  dig www.ruby-lang.org

; <<>> DiG 9.10.6 <<>> www.ruby-lang.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37990
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 0

;; QUESTION SECTION:
;www.ruby-lang.org.		IN	A

;; ANSWER SECTION:
www.ruby-lang.org.	300	IN	CNAME	dualstack.m.shared.global.fastly.net.
dualstack.m.shared.global.fastly.net. 30 IN A	151.101.229.178

;; AUTHORITY SECTION:
fastly.net.		7200	IN	NS	ns3.fastly.net.
fastly.net.		7200	IN	NS	ns4.fastly.net.
fastly.net.		7200	IN	NS	ns1.fastly.net.
fastly.net.		7200	IN	NS	ns2.fastly.net.

;; Query time: 130 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Apr 07 14:01:49 JST 2021
;; MSG SIZE  rcvd: 173
```

**Comment by olivierlacan** [comment]
Howdy folks, I'm not sure why this issue is closed, it's not resolved. 

http://ruby-lang.org still doesn't resolve, neither does https://ruby-lang.org

That's not really acceptable. 
<img width="649" alt="image" src="https://user-images.githubusercontent.com/65950/149199458-fe57aae0-ab2f-4d04-93d1-66167ab76396.png">

We have folks deeply familiar with Heroku available to help, can we please get this done? Who from Ruby core has access to these settings and can take the advice @schneems already submitted in https://github.com/ruby/www.ruby-lang.org/issues/2551#issuecomment-814179340?
