### ISSUE TITLE
Translation for ruby-from-other-languages (zh_cn)

### ISSUE THREAD

**Issue by SteveVallay** [ruby/www.ruby-lang.org#257]
http://www.ruby-lang.org/zh_cn/documentation/ruby-from-other-languages/index.md 
seems not complete.
also some pages without translation : 
http://www.ruby-lang.org/zh_cn/documentation/ruby-from-other-languages/to-ruby-from-c-and-cpp/ 
http://www.ruby-lang.org/zh_cn/documentation/ruby-from-other-languages/to-ruby-from-java/
http://www.ruby-lang.org/zh_cn/documentation/ruby-from-other-languages/to-ruby-from-perl/
http://www.ruby-lang.org/zh_cn/documentation/ruby-from-other-languages/to-ruby-from-php/
http://www.ruby-lang.org/zh_cn/documentation/ruby-from-other-languages/to-ruby-from-python/

**Comment by JuanitoFatas** [comment]
Superseded by #1074.
