### ISSUE TITLE
bugs.ruby-lang.org - update link to wiki about floating point numbers

### ISSUE THREAD

**Issue by wesinator** [ruby/www.ruby-lang.org#2608]
https://bugs.ruby-lang.org/#Floating-point-numbers 

The wiki link here is outdated. 
It should go to https://github.com/rdp/ruby_tutorials_core/wiki/Ruby-Talk-FAQ#floats_imprecise 

Thanks,

**Comment by hsbt** [comment]
Thanks, I update it.
