### ISSUE TITLE
Changing the website ui

### ISSUE THREAD

**Issue by BlairLane22** [ruby/www.ruby-lang.org#2612]
Good afternoon. 

I've got a simple question which is why does the websites ui look so bad? Since this language is primary used by websites, the languages website should be the best out of all of the other languages. We should think of it as selling a product. We want to show what it can do. For Example, companies like Shopify, Strip, AirBnB, Twitch, Soundcloud, Groupon, and also Github. All of these amazing companies have built huge websites using Ruby. So why aren't we advertising that? Looking at the website it should make people want to use the language to make the next big thing. I don't want to sound like a jackass but I love Ruby and it hurts my heart knowing what it is capable of and the only thing to show for it is a poorly designed and unattractive ui.

**Comment by ismailarilik** [comment]
This design was choosen between several designs in a contest. There was several designs which looks more modern, which you might probably like. I think this design was choosen because it is more minimal and useful. But I agree with you about modernism of the website. Current design looks like 20 years old.

**Comment by mame** [comment]
I agree that there is room for improvement. What we need is a designer and a coordinator. Can you volunteer?

FYI: The latest renewal of the site was 8 years ago. https://github.com/ruby/www.ruby-lang.org/issues/74

**Comment by hsbt** [comment]
We always welcome your improvement.
