### ISSUE TITLE
Missing header for Array#append

### ISSUE THREAD

**Issue by by-ron** [ruby/www.ruby-lang.org#2614]
Heading for Array#append is missing/does not populate!

**Comment by hsbt** [comment]
I'm not sure what you mean. If you hope to fix our document or feature, Please file it to https://bugs.ruby-lang.org/

**Comment by by-ron** [comment]
My apologies - here is a screenshot of the Array#append method entry. The **append(\*args) -> self** header is what I was referring to (as seen in **assoc(obj)** below). 


<img width="749" alt="Screenshot 2021-01-18 080607" src="https://user-images.githubusercontent.com/74946987/104913501-104cc380-5964-11eb-8c4f-71f32bbddb28.png">
