### ISSUE TITLE
Ruby 3.0.1 tar not found

### ISSUE THREAD

**Issue by gsum** [ruby/www.ruby-lang.org#2641]
I was trying to install ruby version 3.0.1 using chruby but I got an error `Download of https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.bz2 failed!` Then I looked into https://cache.ruby-lang.org/pub/ruby/3.0/ the tar.bz2 was missing. 

I am not sure if it is the right place to ask to add that tarball or not. If this is not the right place please suggest to me where I can ask for that feel free to close this issue. Thank you. 

To give more context, I ran the command `ruby-install --latest ruby` and the error I got 
```
Downloading https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.bz2 into /Users/ ...
--2021-04-28 13:03:25--  https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.bz2
Resolving cache.ruby-lang.org (cache.ruby-lang.org)... 151.101.149.178
Connecting to cache.ruby-lang.org (cache.ruby-lang.org)|151.101.149.178|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-28 13:03:25 ERROR 404: Not Found.

!!! Download of https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.bz2 failed!
```

**Comment by mame** [comment]
We have stopped distributing .tar.bz2 since 3.0.0. If you want a smaller tarball, please choose .tar.xz. About `ruby-install`, please ask its upstream. I guess [this ticket](https://github.com/postmodern/ruby-install/issues/389) is related.
