### ISSUE TITLE
DNS issue prevents entering `ruby-lang.org` in address bar

### ISSUE THREAD

**Issue by zubin** [ruby/www.ruby-lang.org#2657]
Typing `ruby-lang.org` into the address bar renders a 404.

It's a DNS issue. To illustrate the problem:

```
curl -I http://ruby-lang.org
curl: (6) Could not resolve host: ruby-lang.org
curl -I http://www.ruby-lang.org
HTTP/1.1 200 OK
```

Some DNS providers allow redirecting the root to a CNAME. See [Heroku's guide for adding root domains](https://devcenter.heroku.com/articles/custom-domains#add-a-custom-root-domain).

**Comment by hsbt** [comment]
We also use fastly at the front of heroku app. Do you know the configuration about that?

**Comment by zubin** [comment]
> We also use fastly at the front of heroku app. Do you know the configuration about that?

I believe it's a matter of adding the root domain (`ruby-lang.org`) to Fastly's domain config, as described here: https://docs.fastly.com/en/guides/working-with-domains

So it should end up with `ruby-lang.org` and `www.ruby-lang.org`.

**Comment by ZimbiX** [comment]
I've run into this issue a couple of times over the years. It's even more confusing now that Chrome hides the presence or lack of `www` in the address bar:

![Screenshot from 2021-12-23 18-10-27](https://user-images.githubusercontent.com/2916331/147202542-ab7925ce-7c0c-4a5d-8c78-a53a21bb39f3.png)

**Comment by nurse** [comment]
We introduced redirection from `ruby-lang.org` into `www.ruby-lang.org`, and this issue is resolved.
