### ISSUE TITLE
502 - Meetup's

### ISSUE THREAD

**Issue by ShalokShalom** [ruby/www.ruby-lang.org#2680]
No, not 502 Meetup's 😉 

This link is broken:
https://www.ruby-lang.org/en/community/user-groups/

![Screenshot_2021-07-18_23-57-22](https://user-images.githubusercontent.com/6344099/126083314-221c0a54-8da5-4895-a188-2abfe398385c.png)

**Comment by ShalokShalom** [comment]
And you might wanna use something like this:
https://github.com/endymion/link-checker

Its a bit embarrassing, when the own official homepage cant even maintain itself, when it comes to such simple things. 😬

**Comment by jabawack81** [comment]
Happy to fix this, and look into [Link Checker](https://github.com/endymion/link-checker) as suggested

**Comment by JuanitoFatas** [comment]
Thanks for reporting, @ShalokShalom could you make a Pull Request that removes invalid link for now?
