### ISSUE TITLE
Revert 2690

### ISSUE THREAD

**Issue by tibers** [ruby/www.ruby-lang.org#2694]
Revert #2690 

Pull request:
https://github.com/ruby/www.ruby-lang.org/pull/2693

Justification will be written as a song on myspace.

**Comment by hmdne** [comment]
@hsbt Also this one

**Comment by hmdne** [comment]
Btw. this issue, #2693 and #2695 can be closed as all 3 are about reverts and you just did a revert.

**Comment by hsbt** [comment]
@hmdne Thanks
