### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed in ruby and Ubuntu 14.04

### ISSUE THREAD

**Issue by robertochingon** [ruby/www.ruby-lang.org#2805]
Hi, 

   I have this issue explained here: https://stackoverflow.com/questions/71164059/ssl-connect-returned-1-errno-0-state-error-certificate-verify-failed-in-ruby-an

Could you please help?

**Comment by hsbt** [comment]
You should ask it to https://stackoverflow.com/
