### ISSUE TITLE
'Learning Ruby' link on documentation page redirects to unrelated website

### ISSUE THREAD

**Issue by karansapolia** [ruby/www.ruby-lang.org#2807]
I think the intended https://rubylearning.com/ link is no more. Either the domain ownership might've expired and some other entity bought it, or https://rubylearning.com/ has shifted focus.

If you follow the link from the documentation page:
<img width="673" alt="Screen Shot 2022-03-14 at 14 15 52" src="https://user-images.githubusercontent.com/10175625/158136342-71969714-673f-4c1d-b915-02230a9a2226.png">

You are redirected to a web blog which has no articles/resources on Ruby:
<img width="1440" alt="Screen Shot 2022-03-14 at 14 16 59" src="https://user-images.githubusercontent.com/10175625/158136512-c2a441af-ef93-454d-b776-b5ae95da08e4.png">

This website looks more like a products comparison website and does not have any Ruby notes. I think this link needs to be updated.

**Comment by mateusdeap** [comment]
I don't know if there's still interest on this, but to what site should the link point to?

**Comment by stomar** [comment]
Fixed with #2804, commit ca57fff78edb98dc6ba76246df0b95e3538950ee.

The original content can be found on archive.org; the Ruby tutorial ("Ruby Study Notes") for example here: https://web.archive.org/web/20210816095349/https://rubylearning.com/satishtalim/tutorial.html
