### ISSUE TITLE
Change new line separator while writing to new file

### ISSUE THREAD

**Issue by akshay-kakade-dev** [ruby/www.ruby-lang.org#2859]
The file should ignore the new line characters as separator and content directly on the same line. How to achieve this? I tried to explore the options for File.open but couldn't find much on https://ruby-doc.org/core-2.5.0/File.html.

I got `File::ALT_SEPARATOR ` but as it is constant it won't be updated. Can someone please help?

**Comment by hsbt** [comment]
This repository is NOT the FAQ place. You may need to visit to the https://stackoverflow.com/ .
