### ISSUE TITLE
Update More Info link for `Building from Source` section

### ISSUE THREAD

**Issue by ParadoxV5** [ruby/www.ruby-lang.org#2864]
[Commit `c00feff` removed the `How to compile and install` section from the main `README.md`](https://github.com/ruby/ruby/commit/c00feffb46ac646605adc277b5454e6b067e2d8a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L89-L160), possibly in favour of the separate [`building_ruby.md`](https://github.com/ruby/ruby/blob/HEAD/doc/contributing/building_ruby.md) page.

The More Info link `Building from Source` section of the Installation webpage (e.g.: [`en` page](../blob/HEAD/en/documentation/installation/index.md)) still points to the removed header. It should be updated to link to `building_ruby.md`, either:
* from the master branch on GitHub: https://github.com/ruby/ruby/blob/master/doc/contributing/building_ruby.md
* hosted on `docs.ruby-lang.org`: https://docs.ruby-lang.org/en/master/contributing/building_ruby_md.html
* ~~hosted on `ruby-doc.org`~~ Looks like this one is still hosting the version as released with Ruby 3.1.2 whose `README.md` do have the `How to compile and install` section: https://ruby-doc.org/core-3.1.2/README_md.html#label-How+to+compile+and+install

**Comment by stomar** [comment]
Fixed with #2885.

Thanks for pointing this out.
