### ISSUE TITLE
Improve EOL schedule for Ruby versions

### ISSUE THREAD

**Issue by hsbt** [ruby/www.ruby-lang.org#2965]
I'd like to improve EOL schedule each Ruby versions like:

* https://ubuntu.com/about/release-cycle
* https://devguide.python.org/versions/
* https://www.php.net/supported-versions.php
* https://github.com/nodejs/Release

We have a machine-readable data for this at https://github.com/ruby/www.ruby-lang.org/blob/master/_data/branches.yml.

**Comment by unak** [comment]
The information I think users need is:
- Clarification of Ruby's maintenance schedule principles
  - Stable version with new teeny will be released every December
  - Each teeny is scheduled to move to the security maintenance phase from April two years after the initial release of it
  - The security maintenance phase will last for 1 year, after which it will be EoL
- A cool chart showing the above for each specific version

**Comment by gotoken** [comment]
#2970 should fulfill all unak's advice. I prepared [a simple benchmark](https://gist.github.com/gotoken/125c84ac8456b6fcee9277b2c34098b3).  I'm not sure if the dates in _data/branches.yml for the commits are accurate, so I would appreciate it if you could check. Thanks.

**Comment by JuanitoFatas** [comment]
By the way, there is an existing service called [Ruby | endoflife.date](https://endoflife.date/ruby) that has EOL schedule for Ruby.

![CleanShot 2023-01-30 at 10 11 28@2x](https://user-images.githubusercontent.com/1000669/215367967-18bac3bc-95b5-446e-9464-5433267fc4a5.png)

**Comment by hsbt** [comment]
We can improve this at https://www.ruby-lang.org/en/downloads/branches/. I'll close this.
