### ISSUE TITLE
Ruby Koans URL is broken.

### ISSUE THREAD

**Issue by lbvf50mobile** [ruby/www.ruby-lang.org#3051]
Greetings.

For two days [Ruby Koans](https://www.rubykoans.com/) answer with different nonsense: sometime 502, some times dashboards with graphics and some times with Auth requests.

I started my Ruby journey from Ruby Koans, it is very important resource, and it must be easily accessible. Here is a [pull request](https://github.com/ruby/www.ruby-lang.org/pull/3050) where unstable https://www.rubykoans.com substituted by robust [GitHub source](https://github.com/edgecase/ruby_koans).

https://github.com/ruby/www.ruby-lang.org/pull/3050

Thank you.

![ruby_koans_dash_502](https://user-images.githubusercontent.com/23147487/234975985-5973526e-a8d6-49d9-8f6d-12e247cc7792.png)

**Comment by gfvcastro** [comment]
Hey @lbvf50mobile, apologies for the incident.

I had a discussion with @mdoel about that yesterday, and he told me it was an issue from the [Render](https://render.com/) side.

It is online again. I will close the issue and the pull request.

I wish you the best in your path to learn Ruby.
