### ISSUE TITLE
Latest release, minor version decremented. 3.3.0 -> 3.2.3

### ISSUE THREAD

**Issue by mdalpozzo** [ruby/www.ruby-lang.org#3187]
Latest version is 3.2.3, but last version was 3.3.0... is this a mistake?

**Comment by JuanitoFatas** [comment]
Thanks for asking. What page are you talking about?

**Comment by mdalpozzo** [comment]
https://www.ruby-lang.org/en/

but i just realized this is a patch upgrade from 3.2.2... confused me for a sec!

**Comment by JuanitoFatas** [comment]
Yeah, it is a security release 👍🏻
