### ISSUE TITLE
Strip does not work with invisible characters

### ISSUE THREAD

**Issue by frankyston** [ruby/www.ruby-lang.org#3210]
Currently, strip can clean spaces before and after the string.

However, when placing an invisible character in the string, strip considers it an actual character.

Is this behavior expected?

Below is an example image.

![Screenshot 2024-03-31 at 09 50 42](https://github.com/ruby/www.ruby-lang.org/assets/1836802/c466202d-e693-4abb-b18a-06634f89a441)

website used to get the invisible character: https://www.editpad.org/tool/invisible-character

**Comment by hsbt** [comment]
Can you file it to https://bugs.ruby-lang.org/ or https://stackoverflow.com/?

This repository is not support forum.
