### ISSUE TITLE
3.4.0-preview1 downloads all 404

### ISSUE THREAD

**Issue by tianon** [ruby/www.ruby-lang.org#3245]
I'm not sure if this is just a CDN quirk, but all the links for 3.4.0-preview1 (https://www.ruby-lang.org/en/news/2024/05/16/ruby-3-4-0-preview1-released/) seem to be 404:

```console
$ curl -s --head https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.0-preview1.tar.gz | head -1
HTTP/2 404 
$ curl -s --head https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.0-preview1.tar.xz | head -1
HTTP/2 404 
$ curl -s --head https://cache.ruby-lang.org/pub/ruby/3.4/ruby-3.4.0-preview1.zip | head -1
HTTP/2 404 
```

https://github.com/ruby/www.ruby-lang.org/blob/100af59e84c8f8a01544dd3218eb46e7f507b07a/_data/releases.yml#L33-L35

:bow: :heart:

**Comment by hsbt** [comment]
@tianon Thank you for your mention. I put new packages the correct places now.

Can you try to get them agein?

**Comment by tianon** [comment]
Very nice, appears fine locally :+1:

Thank you!! :heart:

**Comment by tianon** [comment]
(Experiencing some failures in CI which are likely just cached responses -- I'll keep trying them and let you know if they don't seem to resolve with more time. :+1:)

**Comment by tianon** [comment]
Confirmed, all is well. :+1: :heart:
