### ISSUE TITLE
Outdated "getting started" links

### ISSUE THREAD

**Issue by kaya3** [ruby/www.ruby-lang.org#3426]
On the [Documentation](https://www.ruby-lang.org/en/documentation/) page, many of the linked resources appear to be outdated.

Under "Getting Started":

- The official FAQ says the examples have been run using Ruby 2.3.
- poignant.guide doesn't give a version number I can find, but the [GitHub link](https://github.com/mislav/poignant-guide) says it has _"Updated code examples to match Ruby 1.9 behavior"_.
- _Ruby Essentials_ on techtopia.com, under "Getting and Installing Ruby" shows `ruby 1.8.1 (2003-12-25) [i386-linux-gnu]` as the sample output.
- _Learn to Program_ by Chris Pine says _"What's here on this site is the original tutorial, more or less unchanged since 2004"_, though it also links to a textbook which you can buy with a 2021 publication date.
- _Learn Ruby the Hard Way_, clicking through to the web version gives an SSL error, but I can manually switch to HTTP. Then it shows `ruby 2.1.2p95 (2014-05-08 revision 45877)` as the sample output in the setup chapter. There is a Google screenshot which looks like it's also from ~2014 and shows the same version number.

Under "Manuals":

- _Programming Ruby_ says: _"This book documents Version 1.6 of Ruby, which was released in September 2000"_.
- _The Ruby Programming Wikibook_ shows `ruby 1.8.7 (2009-06-12 patchlevel 174) [i486-linux]` as a sample output for `ruby -v`, and the Overview page refers to a feature which _"will disappear in 1.9"_ in the future tense. Those two pages were edited in 2022.

It's possible some of them might be up-to-date despite old version numbers in sample outputs or screenshots. At least, none of the linked pages explicitly say they are accurate for Ruby 3.0 or later. For a new Ruby user (myself) this didn't inspire confidence that the information on those sites would still be accurate.

I was suggested to post this as an issue by @zenspider in the Ruby Discord server.

**Comment by zenspider** [comment]
I've got a branch I've getting :eyes: on and then I'll put up a PR
