### ISSUE TITLE
Staging deployment from Travis CI does not work

### ISSUE THREAD

**Issue by makimoto** [ruby/www.ruby-lang.org#841]
Staging deploying from Travis CI does not work now.
https://travis-ci.org/ruby/www.ruby-lang.org/builds/35776233

Manual deployment with `git push heroku master` works rightly.

@hsbt Do you know anything about this? It may be caused by updating ruby to 2.1.3 and workarounds for it (#837).

**Comment by chikamichi** [comment]
Hi, @hsbt yesterday I merged some commits into master, and had to manually deploy the staging env using `git push heroku`.

**Comment by chikamichi** [comment]
@hsbt @stomar on the same topic, I'm afraid I forgot how to deploy in production :) Could you remind me about the command? Thank you!

**Comment by hsbt** [comment]
@chikamichi Following instructions:

```
$ git remote -v
heroku	git@heroku.com:www-ruby-lang.git (fetch)
heroku	git@heroku.com:www-ruby-lang.git (push)
(snip)
```

if you use heroku name with staging env, you can rename or add alternative name of remote repository like ```production```.

```
$ git remote add production git@heroku.com:www-ruby-lang.git
```

you can deploy production env now.

```
$ git push production
```

**Comment by chikamichi** [comment]
@hsbt then I don't get it: I already have the `heroku` remote set in the same way you demonstrated (`git remote -v`). So to my understanding, git@heroku.com:www-ruby-lang.git is the production env. Yet, when I pushed using `git push heroku`, it updated the staging env, not the production.

**Comment by stomar** [comment]
@chikamichi Is it possible that your local master was not up-to-date when you pushed to heroku?
You pushed an older commit (b9e71c1, `heroku releases` should give you that information).

Staging does seem to work, it shows the latest change of `fr/documentation`.

**Comment by chikamichi** [comment]
Hum, entirely possible. I'll check that.

**Comment by chikamichi** [comment]
Thx @stomar, that was it. I didn't think about simply checking the releases history and commit pointers in `git log` :) I deployed the latest version just fine.
