### ISSUE TITLE
Import patch writer's guide

### ISSUE THREAD

**Issue by zzak** [ruby/www.ruby-lang.org#865]
From the [page on Ruby Core](https://www.ruby-lang.org/en/community/ruby-core/) there is a link to an old post on the mailing list by Matz.
It's called the ["Patch Writer's Guide"](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-core/25139) to contributing to Ruby, and I think would make a welcome addition to the www.ruby-lang.org site.

Who wants to add it so we can start translating it?

**Comment by stomar** [comment]
@zzak I provided a slightliy modified version of the "Patch Writer's Guide" in #893. Any comments?

**Comment by stomar** [comment]
"Patch writers guide" has been merged some time ago. Closing.
