### ISSUE TITLE
rsync://ftp.ruby-lang.org/ down?

### ISSUE THREAD

**Issue by tdb** [ruby/www.ruby-lang.org#905]
The rsync service at rsync://ftp.ruby-lang.org/ appears to be down. Is that intentional? Mirrors need it to be functional to sync the latest content.

Apologies if this is the wrong place to ask this question!

**Comment by chikamichi** [comment]
Hi @tdb,

I couldn't tell you, but maybe @hsbt knows.

**Comment by hsbt** [comment]
@tdb Sorry, too too late response. We did stop distribution via rsync.
