### ISSUE TITLE
fix broken link of documention in Japanese

### ISSUE THREAD

**Issue by hsbt** [ruby/www.ruby-lang.org#94]
FAQ link is broken in http://www.ruby-lang.org/ja/documentation/

https://bugs.ruby-lang.org/issues/5504

**Comment by take** [comment]
Looks like we can close this issue..? Seems like ja/documentation has been updated after 2013. ref: https://github.com/ruby/www.ruby-lang.org/commits/master/ja/documentation

If there's anything I can help please let me know :)

@hsbt @kakutani

**Comment by hsbt** [comment]
@take I see. We need to restart with latest contents.
