### ISSUE TITLE
Update downloads page for 2.2.0

### ISSUE THREAD

**Issue by stomar** [ruby/www.ruby-lang.org#948]
The `downloads` page needs an update, or the 2.0.0 branch is not listed anymore, see e91dd2f6dd5b49258ef879ad928357b9173d2964.

* [X] bg
* [X] de
* [x] es (@dabit)
* [x] fr (@chikamichi, @chatgris)
* [ ] id (@gozali)
* [x] it (@alepore)
* [x] ja (@makimoto)
* [X] ko
* [x] pl (@crabonature)
* [x] pt
* [x] ru (@gazay)
* [ ] tr
* [x] vi (@joneslee85)
* [x] zh_cn (@hlcfan)
* [X] zh_tw (@JuanitoFatas)

**Comment by EduardoBautista** [comment]
The `es` version looks to have been updated.

**Comment by stomar** [comment]
No, it hasn't. The 2.0.0 branch doesn't show up (and the rest of the page is outdated, too).

**Comment by alepore** [comment]
`it` was updated

**Comment by EduardoBautista** [comment]
@stomar ah I see, I can update it if @dabit is too busy.

**Comment by dabit** [comment]
@EduardoBautista please do, I have been meaning to find some time for this but haven't been able to. I can review the PR when you are done. I'll appreciate it.

**Comment by chikamichi** [comment]
This is interesting. It's been two weeks since the issue was created, and the updates were covered for all languages (thx everybody!), but **id**, **pt**, **tr** and **zn_cn** (accordingly to the list).

Should we consider those translations as being inactive?

**Comment by stomar** [comment]
@chikamichi pt, tr already had the "unmaintained" warning, I added the same warning to id, zh_cn with 6c4d74c3fbf0ca69cdce7f438546d38f1ba6b027. (They also lack news translations for quite a long time.)

**Comment by joneslee85** [comment]
any update on this?
