### ISSUE TITLE
Maintainer application (bg)

### ISSUE THREAD

**Issue by gmitrev** [ruby/www.ruby-lang.org#962]
Hello everybody!

My name is Georgi and I live in Sofia, Bulgaria. 

I've been using Ruby professionally for more than 3 years and love the language. I would like to keep the Bulgarian version of the site up-to-date and also help with whatever else I can. 

Thanks!

**Comment by stomar** [comment]
cc @hsbt

:+1:

gmitrev did great work in the `bg` section recently.

**Comment by hsbt** [comment]
@gmitrev I added commit bit to you. Welcome!

**Comment by JuanitoFatas** [comment]
Welcome :+1:

**Comment by gmitrev** [comment]
Thank you!
