### ISSUE TITLE
Missing nightly snapshot

### ISSUE THREAD

**Issue by eagletmt** [ruby/www.ruby-lang.org#963]
There's a link to nightly snapshot https://ftp.ruby-lang.org/pub/ruby/snapshot.tar.gz , but it's 404.

**Comment by hsbt** [comment]
@eagletmt Thanks for your report. I'll investigate this.

**Comment by hsbt** [comment]
I solved this.

snapshot script is only work with Ruby 2.0 or later. but our system ruby version is 1.9 in ftp.r-l.o :imp: 

Thanks

**Comment by eagletmt** [comment]
:+1:

**Comment by stomar** [comment]
@hsbt The stable and nightly snapshot links are still (or again) 404.

https://ftp.ruby-lang.org/pub/ruby/snapshot.tar.gz
https://ftp.ruby-lang.org/pub/ruby/stable-snapshot.tar.gz

**Comment by hsbt** [comment]
@stomar Thanks notification. package script only run after Ruby 2.2 :smiling_imp: I fixed server configuration and regenerate these packages.
