### ISSUE TITLE
1.9.3 end of life announcement

### ISSUE THREAD

**Issue by olivierlacan** [ruby/www.ruby-lang.org#976]
I would have missed the actual end of life of 1.9.3 if it weren't for @rafaelfranca's tweet today: https://twitter.com/rafaelfranca/status/569915266160840704

Is there any reason why we don't mirror the maintenance mode announcement with an end-of-life one today? https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

**Comment by hsbt** [comment]
merged at https://github.com/ruby/www.ruby-lang.org/pull/977
