### ISSUE TITLE
Rework or remove top-projects page

### ISSUE THREAD

**Issue by stomar** [ruby/www.ruby-lang.org#98]
(This does not have highest priority.)

The top-projects page a long time(?) ago showed the most highly ranked projects from Rubyforge. At some point the list has been removed, probably because it was completely outdated.

It should be re-thought from scratch whether there should be a top projects page at all, and--if yes--what it's content might be.

**Comment by ismailarilik** [comment]
Shouldn't this issue be closed after the PR #608?

**Comment by siaw23** [comment]
Agree with @ismailarilik, I think this should be close after https://github.com/ruby/www.ruby-lang.org/pull/608 @hsbt what do you think? :)
